### ISSUE TITLE
Terraform deployment request shows error even thought the machine is eventually deployed

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#10]
terraform config file (.tf)

provider "cas" {
  url = "https://api.staging.symphony-dev.com"
  refresh_token = "xxxxxxxxxxxxxxxxxxxx"
  deployment_id = "cas_machine_tf_test"
}

resource "cas_machine" "my_ubuntu_machine" {
    name = "terraform_provider_cas_machine"
    flavor = "small"
    image = "ubuntu"
}

After running terraform apply and approving the plan I see the below error

Error: Error applying plan:

1 error(s) occurred:

* cas_machine.my_ubuntu_machine: 1 error(s) occurred:

* cas_machine.my_ubuntu_machine: 
Request: /iaas/machines create resource
POST https://api.staging.symphony-dev.com/iaas/machines HTTP/1.1
Host: api.staging.symphony-dev.com
authorization: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
content-type: application/json
{"name":"terraform_provider_cas_machine","image":"ubuntu","flavor":"small","projectId":"a2144353-b449-4844-9191-e3087c1dcafb","machineCount":1,"customProperties":{"__composition_context_id":"cas_machine_tf_test"},"nics":[]}
Response status code: 201
Response body: {"progress":0,"status":"INPROGRESS","name":"Provisioning","id":"d21b1de9dcb252755861d87253b38","selfLink":"/iaas/api/request-tracker/d21b1de9dcb252755861d87253b38"}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by dmettem** [comment]
@pmamtora I'm closing the issue as I haven't heard back. Please reopen if you see the issue.
