### ISSUE TITLE
vra_deployment can not run as an update

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#100]
When running a vra_blueprint you can only do a deployment. 
In vra it allows you to update a deployment which does an update operation

Example:

I have 3 machines in the blueprint and remove one and re-run terraform apply it says deployment name already exists.  In vra you can run an update deployment and it would remove the vm.

2019/11/11 10:44:47 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate

2019/11/11 10:44:47 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
Error: a deployment with name 'tf1' exists already. Try with a differnet name

  on main.tf line 16, in resource "vra_deployment" "this":
  16: resource "vra_deployment" "this" {

**Comment by dmettem** [comment]
@mdittbrenner215 
I don't think I understood the issue here. There is no `vra_blueprint` resource available yet.
Are you trying to update a `vra_deployment` resource (that is originally deployed with a blueprint) after making changes to the blueprint in vRA?

**Comment by mdittbrenner215** [comment]
Sorry i think you are right. This should be need vra_deployment resource then.  We can deploy with the data but cant do any updates to the deployment once its deployed.

**Comment by dmettem** [comment]
Current update on deployment only supports changes to name and description.

When `terraform apply` is run the first time with a blueprint id and version, the deployment gets created and tf state is stored. If the `terraform apply` is run again without any config changes in main.tf, no changes are applied today even if the underlying blueprint is changed. This is useful for deployments made from blueprint current draft version. I guess, this is the case you are trying and noticed not working. Is that right? @mdittbrenner215 

If the deployment needs to be updated to another version of the blueprint, it would require change to main.tf and when the blueprint_version is updated, running `terraform apply` again should update the existing deployment.

**Comment by mdittbrenner215** [comment]
I think we need to get past the crash bug first, but the original use case i had was if we changed the number of VMs and increase or decrease which changes variables in the main.tf.

**Comment by dmettem** [comment]
That makes sense. I think you are referring to crash issue reported in #101. Sure, I'll try to get a PR out later today for the crash issue fix. I need to test few more cases before sending out for review.

**Comment by mdittbrenner215** [comment]
Hey Deepak . figured id swing back to this since since the crash in #101 was fixed.

So if i have a deployment created that has an input of 3 machines.  Say I then update my input to 5 machines when i run this it shows a change but doesnt actually deploy the additional machines.

**Comment by dmettem** [comment]
@mdittbrenner215 Thanks for validating the fix for #101.

Currently the provider doesn’t change the deployment topology but only name and description during the update. Update requires special handling for in-place deployment topology change. I'll keep you posted on the progress for this issue.

**Comment by AnjaliMangal** [comment]
This is WIP now and fix will bne available in plugin , we shall have an update in next week  .

**Comment by dmettem** [comment]
Fixed via #136. Part of release [v0.1.7](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.7).

@mdittbrenner215 Please verify.
