### ISSUE TITLE
Installation documentation not clear

### ISSUE THREAD

**Issue by cferber** [vmware/terraform-provider-vra#102]
To ease installation for non-developers you should add instruction:
- where to download binary (link to releases)
- how to extract binary
- where to put provider file (.terraform.d/plugins)

**Comment by dmettem** [comment]
We will work on adding the documentation with steps to download and install the plugin.

**Comment by cars** [comment]
@dmettem I can take a run at this.

**Comment by dmettem** [comment]
Sure @cars. I appreciate that. Thank You!

**Comment by dmettem** [comment]
@cars Assigned to you so that no one duplicates the effort.

**Comment by cars** [comment]
@cferber  can you check #109 and see if it addresses this sufficiently?

**Comment by cferber** [comment]
@cars Yes, this looks fine from my perspective. Not sure where this file is being put. For ease of use it should be part of readme.md or at least a reference from it. 
Thanks!

**Comment by cars** [comment]
@cferber  I've updated the PR to include a link to the file in the main readme.md

**Comment by dmettem** [comment]
Fixed in #109.
