### ISSUE TITLE
Customer wants to deploy XaaS blueprints

### ISSUE THREAD

**Issue by cferber** [vmware/terraform-provider-vra#103]
Provider talks to Cloud Assembly currently.
Customer has an XaaS service which is exposed in Service Broker.
Use Case: Customer wants invoke a REST operation on a 3rd party system and populated forms by dynamic values. 
How can this be done through terraform provider?

**Comment by cars** [comment]
If you want to call XaaS you can treat it just as another catalog item using the deployment resource. Example as follows: 
vRO workflow ``CRT_SB_TEST_SIMPLE`` published in Service Broker 

![vra8_sb_catalog](https://user-images.githubusercontent.com/137110/68798342-1e3de080-060b-11ea-82cf-7df1eb8f33bd.png)

It's a simple one that just takes two input string and then spits them back out as output strings
![vra8_sb_vro_form](https://user-images.githubusercontent.com/137110/68798411-3c0b4580-060b-11ea-8141-e60713843406.png)

Then using the following I can execute the workflow (not using vars here for brevity)

```terraform
provider "vra" {
  #Pulling values from ENV for URL and Refresh Token
  #url           = var.url
  #refresh_token = var.refresh_token
  #insecure      = var.insecure
}

data "vra_project" "this" {
  name = "My First Project"
}

data "vra_catalog_item" "this" {
  name            = "CRT_SB_TEST_SIMPLE"
  expand_versions = true
}

resource "vra_deployment" "this" {
  name        = "tf_vro_test"
  description = "terraform test deployment"

  catalog_item_id      = data.vra_catalog_item.this.id
  project_id           = data.vra_project.this.id

  inputs = {
    inputstring1   = "this is my first input string"
    inputstring2    = "this is my second input string"
  }
  expand_resources    = true
  expand_last_request = true
}

output "projectinfo" {
  value = data.vra_project.this
}

output "cataloginfo" {
  value = data.vra_catalog_item.this
}

output "deploymentinfo" {
  value = vra_deployment.this
}
```

We can see afterwards it's run: 
![vra8_sb_vro_dep](https://user-images.githubusercontent.com/137110/68799170-8c36d780-060c-11ea-89bc-97a8fb01a592.png)

and in the terminal where I ran ``terraform apply`` we get the output for _deploymentinfo_ where we can see the input and output strings.
![vra8_sb_vro_output](https://user-images.githubusercontent.com/137110/68799274-bab4b280-060c-11ea-83ab-9e1667c1fc66.png)

This is a pretty simple example, so I don't know how easy (or if possible) to get/manipulate the values of more dynamic forms (ex:dropdowns and such) if you're using those...

**Comment by dmettem** [comment]
Thanks @cars for the detailed example.
@cferber Did you get a chance to try this out? Let us know if you have any particular questions or run into an issue.

**Comment by dmettem** [comment]
@cferber Closing this issue as there is no update for over 90 days. Feel free to reopen if you need further. assistance.
