### ISSUE TITLE
Supported Versions of vRA

### ISSUE THREAD

**Issue by pezhore** [vmware/terraform-provider-vra#107]
Can someone share/update the documentation to indicate what version(s) of vRA this provider supports? Current documentation seems to reference CAS/vRA 8 things, but I'm not sure if that's accurate.

**Comment by cars** [comment]
There's a separate provider for vra7  at https://github.com/terraform-providers/terraform-provider-vra7

**Comment by cars** [comment]
I've submitted #108 to address this..

**Comment by dmettem** [comment]
Thanks @pezhore for reporting and @cars for updating the supported versions. Closing the issue now.
