### ISSUE TITLE
Data source for projects returns error if the org has more than 500 projects

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#110]
The API called to get the projects may not be using the queryparams/filter while making the API call. Instead it appears to be fetching all projects and then applying the filter. This breaks if I have more than 500 projects as the project that is being searched for is not present in the 500 returned projects

**Comment by dmettem** [comment]
As I reported to @pmamtora offline, updating for visibility of others, this will be fixed soon.

**Comment by dmettem** [comment]
Fixed in #126.
