### ISSUE TITLE
Updating the disk size does not resize the disk

### ISSUE THREAD

**Issue by sbadem** [vmware/terraform-provider-vra#115]
Changing the disk size should update the disk

**Comment by mdittbrenner215** [comment]
Is this with deployment or using IAAS?  deployment no updates work.  This is #100

**Comment by AnjaliMangal** [comment]
Need more clarification on this use case , we will get back with update soon .

**Comment by Prativa20** [comment]
@sbadem The product currently doesn't support updating the disk size through iaas APIs. We will contact the product team to see what is their plan for this feature.

**Comment by markpeek** [comment]
Fixed via #130
