### ISSUE TITLE
Need data source for vra_block_device to manage attach/detach disk in multple iterations

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#123]
I am trying the use case wherein I provision a vra_block_device first. And follow up with provisoning a vra_machine and attach the provisioned vra_block_device to it.

Iteration 1: provision vra_block_device

provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure      = var.insecure
}

data "vra_project" "this" {
  name        = "e2e-terraform-vra-prithvish"
}

resource "vra_block_device" "disk1" {
  capacity_in_gb = 10
  name = "terraform_vra_block_device_1"
  project_id = data.vra_project.this.id
}

Iteration 2:  provision a machine and attach the provisioned disk in 1) to it

provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure      = var.insecure
}

data "vra_project" "this" {
  name        = "e2e-terraform-vra-prithvish"
}

resource "vra_machine" "vms" {
  count = var.instance_count
  description = "terraform vra_machine"
  project_id  = data.vra_project.this.id
  name        = "tf-prithvish-machine-with-disk"
  image       = "ubuntu"
  flavor      = "small"
  tags {
          key = "foo"
          value = "bar"
  }
  tags {
      key   = "OS"
      value = "Ubuntu"
  }
  disks {
      block_device_id = data.vra_block_device.this.id
  }

  timeouts {
        create = "20m"
  }
}

data "vra_block_device" "this" {
  name        = "terraform_vra_block_device1"
}

I get the following error when I do terraform apply

Error: Invalid data source

  on main.tf line 35, in data "vra_block_device" "this":
  35: data "vra_block_device" "this" {

The provider provider.vra does not support data source "vra_block_device".

NOTE: As a workaround I am able to hardcode block_device_id in the Iteration 2

**Comment by Prativa20** [comment]
Fixed as part of this #133
