### ISSUE TITLE
Destroying  machine also deletes the attached disk

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#124]
Following up after the workaround in https://github.com/vmware/terraform-provider-vra/issues/123

I did `terraform apply` for the following main.tf file and was able to provision a machine and attach the pre-created disk to it. 

In the second iteration I did `terraform destroy` and the machine as well as the attached disk. However, it was expected that it will only detach the disk and delete the machine. 

provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure      = var.insecure
}

data "vra_project" "this" {
  name        = "e2e-terraform-vra-prithvish"
}

resource "vra_machine" "vms" {
  count = var.instance_count
  description = "terraform vra_machine"
  project_id  = data.vra_project.this.id
  name        = "tf-prithvish-machine-with-disk"
  image       = "ubuntu"
  flavor      = "small"
  tags {
          key = "foo"
          value = "bar"
  }
  tags {
      key   = "OS"
      value = "Ubuntu"
  }
  disks {
      block_device_id = "5c1dfebfc275ba75599394155c558"
  }

  timeouts {
        create = "20m"
  }
}

**Comment by Prativa20** [comment]
Handled as part of https://github.com/vmware/terraform-provider-vra/pull/150
If persistent is set for the attached block device resource, it will not be deleted when machine is deleted.
