### ISSUE TITLE
vra_block_device should support updating tags

### ISSUE THREAD

**Issue by sbadem** [vmware/terraform-provider-vra#127]
Tag update is not supported. It could be either new tags or updating existing tags (keys) with a different value

**Comment by dmettem** [comment]
@Prativa20 As you are already working on the disk resize functionality, can you please take care of this as well?

**Comment by dmettem** [comment]
@Prativa20 Can you please verify if this has been fixed in vRA 8.0.1 or upcoming vRA 8.1?

**Comment by Prativa20** [comment]
The support for this in the product is being prioritized for next on-prem releases.
