### ISSUE TITLE
vra_block_device should have a persistent attribute

### ISSUE THREAD

**Issue by sbadem** [vmware/terraform-provider-vra#128]
When persistent= true for a vra_block_device, then when removing the vm during terraform update action, then the disk should not be deleted even though the vm is gone.

**Comment by dmettem** [comment]
@sbadem vra_block_device is destroyed only when it is removed from the config file. However, the DELETE IaaS machine API deletes the disks attached to the machine irrespective of the `persistent` flag value on the block device.
Have you tried this with IaaS APIs directly? If so, you would notice the same issue. Marking it as product issue and will track internally with the right team.

**Comment by dmettem** [comment]
This is similar to #124.

**Comment by Prativa20** [comment]
Added persistent attribute for block-device resource https://github.com/vmware/terraform-provider-vra/pull/150
