### ISSUE TITLE
vra_machine submitting in batches

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#134]
Looks like in the newer verison vra_machine (iaas api) is submitting in batches of 10.  It then waits for the 10 to complete before submitting the next batch.  

Not sure if this is expected behavior, but if it is we should have a parameter to change batch size.
It took me 2.5 hours to provision 100 VMs today.

This is vra 8 on-prem and verified on vra 8 and vra 8.0.1 RC

**Comment by markpeek** [comment]
Could this be due to the [parallelism](https://www.terraform.io/docs/commands/apply.html#parallelism-n) limit?

**Comment by mdittbrenner215** [comment]
I’ll check but I didn’t do it before which is odd..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mdittbrenner215** [comment]
yes is it.  Weird when i built it originally i didnt have to use that switch, but it was when i was building the provider manually.
