### ISSUE TITLE
Requesting support for fabric-vsphere-storage-policies & fabric-vsphere-datastores data source

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#137]
Requesting support for fabric-vsphere-storage-policies & fabric-vsphere-datastores data source to avoid hardcoding of storagePolicyId & datastoreId when creating vsphere storage profiles

**Comment by dmettem** [comment]
This is fixed and released in [v0.3.3](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.3.3).

**Comment by production-tango** [comment]
Verified, thanks Deepak!
