### ISSUE TITLE
Regions Not Working with vSphere Cloud Account

### ISSUE THREAD

**Issue by kclinden** [vmware/terraform-provider-vra#139]
When using the example file that is available [here](https://github.com/vmware/terraform-provider-vra/tree/master/examples/cloud_account_vsphere) I am unable to successfully enumerate the regions. vCenter. 

Hard coding the regions works, but it does not work with the data object. 

Worked with @dmettem to troubleshoot this issue.

Log File:
[terraform.log](https://github.com/vmware/terraform-provider-vra/files/3983515/terraform.log)

**Comment by kclinden** [comment]
Will add more logs this evening.

**Comment by dmettem** [comment]
**Environment info:**
vRA Version: 8.0 GA
Terraform Version: 0.12.8
OS: Windows

**Comment by kclinden** [comment]
This also occurred when using the WSL for Linux with Ubuntu.

**Comment by kclinden** [comment]
Log Added for Windows.

**Comment by cars** [comment]
This may be an issue with the swagger docs...  according to swagger the enumeration request should be returning a 200 response code (https://code.vmware.com/apis/655/vra-cloud-iaas-rest#/Cloud%20Account/enumerateVSphereRegions) it looks (at least in my lab) like it's returning a 201 instead and that's being interpreted as an error. 
![tf_vra_error](https://user-images.githubusercontent.com/137110/71562869-81f55f00-2a3b-11ea-8f61-6f143ca4f7e5.png)
[TF.log](https://github.com/vmware/terraform-provider-vra/files/4008564/TF.log)

**Comment by cars** [comment]
So looks like maybe the culprit is in vra-sdk-go? 
https://github.com/vmware/vra-sdk-go/blob/a5f8b2608f8e7d140365741af42d7252a20f8ec2/pkg/client/cloud_account/enumerate_vsphere_regions_responses.go#L27

**Comment by cars** [comment]
So after some further digging, there might be two issues here... one is the swagger  mismatch between what the swagger spec is  RC of 200 vs 201 at least in VRA 8.0.1. Looking at the terraform.log @kclinden  attached the response code is in that session is 200.  So I don't know if this changed between 8.0GA and 8.0.1 or not. But even after tweaking enumerate_regions_response.go from the vra_sdk to get past the 201 return code issue the it still appears the data source does not work correctly.

**Comment by dmettem** [comment]
@cars I assigned this to you as you are working on it. Thanks for the contribution!

**Comment by dmettem** [comment]
This is fixed in [v0.1.9](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.9).
Dedicated `vra_region_enumeration_vsphere` data source also exists now and it works the same way as `vra_region_enumeration` data source which will be deprecated soon in the support of dedicated data sources for different cloud account regions enumeration.
