### ISSUE TITLE
Count not working unless 1

### ISSUE THREAD

**Issue by ameya-r** [vmware/terraform-provider-vra#145]
Observing issue for vRACloud Assembly provider.
Using : terraform-provider-vra-linux_amd64-v0.1.6.tgz

When count = 2 (more than 1), getting below error :   
Error: [GET /deployment/api/deployments/{depId}][404] getDeploymentByIdUsingGETNotFound

Snippet :
provider "vra" {
  url           = "https://vra_domain"
  refresh_token = "XXXXXXXXXXXXXXX"
  insecure      = true
}

data "vra_project" "this" {
  name = "TEST"
}
resource "vra_deployment" "this" {
  count       = 2
  name        = "Test Blueprint Deployment"
  description = "terraform test deployment"

  blueprint_id      = "xxxxx-xxxxx-xxxx-xxxx"
  blueprint_version = ""
  project_id        = data.vra_project.this.id

  inputs = {
    flavor = "small"
    image  = "centos"
    count  = 2
    flag   = true
  }

  timeouts {
    create = "60m"
    delete = "2h"
  }

  expand_resources    = true
  expand_last_request = true
}

Output with Error: 
vra_deployment.this[1]: Creating...
vra_deployment.this[0]: Creating...
vra_deployment.this[1]: Still creating... [10s elapsed]
vra_deployment.this[1]: Still creating... [20s elapsed]
........
.......
vra_deployment.this[1]: Still creating... [15m0s elapsed]
vra_deployment.this[1]: Still creating... [15m10s elapsed]
vra_deployment.this[1]: Still creating... [15m20s elapsed]
vra_deployment.this[1]: Creation complete after 15m23s [id=xxxxxx-xxxx-xxxx-xxxxxx]

Error: [GET /deployment/api/deployments/{depId}][404] getDeploymentByIdUsingGETNotFound

  on vra_blueprint.tf line 12, in resource "vra_deployment" "this":
  12: resource "vra_deployment" "this" {

Where as, it successfully runs with count=1

**Comment by mdittbrenner215** [comment]
Wouldn’t you get an error for duplicate deployment names since you are not increment that name also?

**Comment by ameya-r** [comment]
Initially, it does show :
vra_deployment.this[1]: Creating...
vra_deployment.this[0]: Creating...

But then it starts with "vra_deployment.this[1]: Creating..."
My scenario is I want to deploy multiple VM's using same resource. Hence, trying to increment count as 2.
Can you please point to an example where I can increment deployment names or correct use of "count" (greater than 1)

**Comment by ameya-r** [comment]
> @mdittbrenner215 :
> Initially, it does show :
> vra_deployment.this[1]: Creating...
> vra_deployment.this[0]: Creating...
> 
> But then it starts with "vra_deployment.this[1]: Creating..."
> My scenario is I want to deploy multiple VM's using same resource. Hence, trying to increment count as 2.
> Can you please point to an example where I can increment deployment names or correct use of "count" (greater than 1)

Any update here?

**Comment by dmettem** [comment]
@ameya-r - Please try with [random-integer](https://www.terraform.io/docs/providers/random/r/integer.html) as suffix in deployment name.

**Comment by mdittbrenner215** [comment]
So if you want more than one machine per deployment you may need to change your blueprint. 
By adding count to vra_deployment you are creating multiple deployments not multiple machines per depoyment.

In my case we did an input on the blueprint for called count and that is a vsphere machine property count and that creates multiple machines PER deployment.

**Comment by ameya-r** [comment]
As per example (of vRA7 provider) : https://www.terraform.io/docs/providers/vra7/r/deployment.html

we tried using resource_configuration parameter in terraform script since we configured count parameter in blueprint.
But after triggering "terraform plan" command, giving following error : 
**An argument named "resource_configuration" is not expected here.**

**Comment by mdittbrenner215** [comment]
This is for vra cloud and vra 8 on prem. It does not work with vra 7 and the documentation for vra provider 7 does not work for this provider.

**Comment by ameya-r** [comment]
Using vRA 8.0.0.6619 (14842736) and its not working for this version.

**Comment by ameya-r** [comment]
> Using vRA 8.0.0.6619 (14842736) and its not working for this version.

Any updates here?

**Comment by dmettem** [comment]
@ameya-r Thanks for confirming that you are using this provider with vRA 8.0.

From the description in the issue, it appears that you want to create more than one deployment with same blueprint. If so, you have to make sure that deployment name is different for each of the deployments as the count is > 1. One way to achieve it is by using the random functions in terraform. This will result in more than one deployment that you can manage individually from vRA UI.

If you want to create only one deployment with multiple resources (VMs) as defined in the blueprint, as @mdittbrenner215  suggested, you would have to change your blueprint to make the count on the resource as an input and pass that input from terraform config file in the deployment resource.

Please provide which of the above use cases you are trying to achieve. Thanks!

**Comment by ameya-r** [comment]
My scenario is second one : one deployment with multiple resources (VMs).

As per previous comments from @mdittbrenner215 , tried passing count parameter to blueprint which is not reflecting while triggering from terraform.

Can you please post an example of blueprint conf and terraform script to pass the count from terraform script to blueprint?

Thanks!

**Comment by dmettem** [comment]
Here's how the Blueprint referred in the catalog would look like that includes the count:
```
formatVersion: 1
    inputs:
      image:
        type: string
        description: "Image"
      flavor:
        type: string
        description: "Flavor"
    count:
      type: integer
      description: "Number of machines"
    resources:
      Machine:
        type: Cloud.Machine
        properties:
          image: ${input.image}
          flavor: ${input.flavor}
          count: ${input.count}
```
Refer to the [blueprint example](https://github.com/vmware/terraform-provider-vra/blob/master/examples/blueprint/main.tf) for the creating a blueprint and use the sample above to include count in your blueprint.

Also refer to deployment examples with [catalog item](https://github.com/vmware/terraform-provider-vra/blob/master/examples/deployment/catalog_item/main.tf) and [blueprint](https://github.com/vmware/terraform-provider-vra/blob/master/examples/deployment/blueprint/main.tf) on how to pass the inputs while requesting a deployment.

Keep us posted on how your testing goes.

**Comment by dmettem** [comment]
@ameya-r Can this be closed? Do you still see an issue?

**Comment by dmettem** [comment]
@ameya-r I'm closing the issue as I haven't heard back if this is still an issue. Please create a new issue if there is still a problem.
