### ISSUE TITLE
provider URL is only using host

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#147]
Looks like the URL is not using the full URL and is using only the host attribute.  In our case we are proxying terraform before it hits vra.

So when we use URL when i run directly against vra using below
url = "https://vrahost.com/api/terraformassist/v1/vRA/region1/az1/sadf-adsfd-asdf-asdf"
this should fail but doesnt since it just uses the https://vrahost.com part.

**Comment by mdittbrenner215** [comment]
In our case we play on putting info in part of the URL that then hits a proxy/routing engine.  It will then using info from the URL to route to the correct vra  which will then fix the URL.  

It looks like the provider is only using the host since when i put the extra data in the URL and go directly to vra (bypassing the routing engine) it is working correctly.

**Comment by mdittbrenner215** [comment]
looks like this may be in client.go

getToken() and getAPIClient() are parsing URL.host

**Comment by markpeek** [comment]
Right, I think the quick fix is to replace the two lines in client.go that look like this:
```transport := httptransport.New(parsedURL.Host, "", nil)```

**Comment by markpeek** [comment]
Right, I think the quick fix is to replace the two lines that look like this in client.go:
```transport := httptransport.New(parsedURL.Host, "", nil)```
with
```transport := httptransport.New(parsedURL.Host, parsedURL.Path, nil)```

But to fully test we'll have to get this setup in our lab and also look at the edge cases of having a trailing / in the path.
