### ISSUE TITLE
Creating Project with vSphere Memory Limit

### ISSUE THREAD

**Issue by vrabbi** [vmware/terraform-provider-vra#152]
currently it seems the provider does not support adding a memory limit for vSphere Cloud Zone while creating a project.

**Comment by cars** [comment]
It  looks like maybe the memory limit wasn't in the swagger spec in the version used previously in the vra-sdk-go project so isn't currently in the model https://github.com/vmware/vra-sdk-go/blob/master/pkg/models/zone_assignment_config.go#L16-L26  I do see it does appear to be  present now  (https://www.mgmt.cloud.vmware.com/iaas/api/swagger/ui/ ...look at the ZoneAssignment model)  

So this will require an update to and new release of the vra-sdk-go project...

**Comment by dmettem** [comment]
This is fixed in [v0.1.9](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.9).

**Comment by dmettem** [comment]
@vrabbi Please close the issue if it is working for you.
