### ISSUE TITLE
Apply does not change the number of VMs created by the vRA blueprint

### ISSUE THREAD

**Issue by spbarbieri** [vmware/terraform-provider-vra#155]
I have a vRA blueprint that contains a cluster of 1 to 5 EC2 Servers:

![image](https://user-images.githubusercontent.com/25961207/74564397-02651600-4f3d-11ea-846a-a19b10fe8d14.png)

I have a terraform configuration that deploys this blueprint
```
resource "vra7_deployment" "min_max" {
  wait_timeout = "20"
  catalog_item_name = "min-max"

  resource_configuration = {
    EC2_Cluster._cluster = "3"
    EC2_Cluster.ip_address = ""
  }
}
```

This successfully deploys my blueprint and creates 3 VMs. 

If I change **EC2_Cluster._cluster = "3"** to **EC2_Cluster._cluster = "5"** and run Terraform apply the apply completes successfully but does nothing. I don't get 2 new VMs.

Is this expected? Am I doing something incorrectly?

**Comment by mdittbrenner215** [comment]
This is the terraform provider for vra 8 not 7

**Comment by spbarbieri** [comment]
Thanks, moved to https://github.com/vmware/terraform-provider-vra7/issues/165
