### ISSUE TITLE
vCenter Image Profile created by Terraform lacks the Image Mapping

### ISSUE THREAD

**Issue by sammcgeown** [vmware/terraform-provider-vra#160]
If you create a "vra_image_profile" for a vCenter image using code as below:

```
resource "vra_image_profile" "packer-test" {
  name        = "packer-test-profile"
  description = "Packer Test Image Profile"
  region_id   = data.vra_region.this.id

  image_mapping {
    name       = "CentOS7"
    image_name = "packer-centos7-template"
  }
}
```

The mapped image name is saved, however the image details are not expanded. This means that the image profile throws an error when you try and deploy from it:

`Provisioning operation failed. Expected vc:// scheme, found packer-centos7-template`

If I manually select the image in the UI, the deployments work as expected.

**Comment by Prativa20** [comment]
We are looking at it in the upcoming sprint.

**Comment by dmettem** [comment]
@sammcgeown I need to investigate if it is the same behavior when done with API directly, instead of provider. In the interim, here's the workaround you may try:

`data "vra_image" "ubuntu" {
			filter = "name eq 'packer-centos7-template'"
}

resource "vra_image_profile" "this" {
  name        = "TF-vRA-Provider Image Profile"
  description = "Created for TF-vRA Provider Demo"
  region_id   = data.vra_region.this.id

  image_mapping {
    name       = "Ubuntu"
    image_id   = data.vra_image.ubuntu.id
  }
}`

**Comment by dmettem** [comment]
@sammcgeown - I've tested this even from the UI. When the template name is typed in the image name, all the images matching the entered text are filtered. Image name (entered text) is expanded to the image id only if the user selects the desired image from the filtered list. If the image mapping is created without selecting the image from the list, it is not expanded by default, and deployment fails.

Terraform provider mimics the API behavior. Please use the data source `vra_image` to find the image id and use `image_id` in the `image_mapping`. For AWS, you may even use the AMI as `image_name` without having to use the `image_id` data source.

Closing the issue as this is similar to product behavior.
