### ISSUE TITLE
Provider version not printed

### ISSUE THREAD

**Issue by bortek** [vmware/terraform-provider-vra#171]
Unfortunately it is not possible to check which version of the provider is installed. terraform -version prints terraform's vertsion but states that plugin is unversioned.

terraform -version
Terraform v0.12.23
+ provider.vra (unversioned)

**Comment by dmettem** [comment]
You can get the version of the provider by running the command `terraform-provider-vra -v` on the unpacked plugin file.

Here's the sample output for getting the version of the plugin:
`./terraform-provider-vra -v
version: v0.1.8
build time: 2020-01-14T00:33:46UTC`

I'm also making the change to include it in the `terraform -version` command output.

**Comment by dmettem** [comment]
@bortek This is fixed in latest version [v0.1.9](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.9). Can you please try with the new version of the provider and let me know if you are able to see the version?

**Comment by bortek** [comment]
Thanks. Version number is being printed correctly now.
