### ISSUE TITLE
associate nsx-t/nsx-v cloud account to vSphere cloud account

### ISSUE THREAD

**Issue by vrabbi** [vmware/terraform-provider-vra#173]
the capability should be added to allow associating a nsx-t / nsx-v cloud account with a vSphere cloud account

**Comment by dmettem** [comment]
I agree that the provider should be able to associate NSX cloud accounts with vSphere and vice-versa. We will add this enhancement in the upcoming release.

**Comment by dmettem** [comment]
@vrabbi This is fixed in latest version [v0.1.9](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.9).

**Comment by dmettem** [comment]
Closed via #184.
