### ISSUE TITLE
data vra_region_enumeration_vsphere return  context deadline exceeded

### ISSUE THREAD

**Issue by vvinnich** [vmware/terraform-provider-vra#174]
data "vra_region_enumeration_vsphere" "this" {
  hostname = var.vcenter_hostname
  password = var.vcenter_password
  username = var.vcenter_username
  dcid =  var.dcid
}

Error: Post "https://api.mgmt.cloud.vmware.com/iaas/api/cloud-accounts-vsphere/region-enumeration": context deadline exceeded

When I make this request with same fields (hostname,  password,  username, dcid ) through curl, the response time is more than 30-40s and it works, 
may need to change the timeouts or add timeout block

**Comment by dmettem** [comment]
@vvinnich Provider version [v0.1.9](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.9) is released. Can you please try with the new version of the provider and let me know if this is resolved?

**Comment by vvinnich** [comment]
@dmettem looks like resolved

**Comment by dmettem** [comment]
Thanks for confirmation! Closing the issue.
