### ISSUE TITLE
resource "vra_flavor_profile"  creates object incorrect object for VMC "account/region"

### ISSUE THREAD

**Issue by vvinnich** [vmware/terraform-provider-vra#175]
resource "vra_flavor_profile"  creates object incorrect object for VMC "account/region" without mapping for the current region. In Cloud Assembly UI I can see only Flavour name, but Configuration Account filed without any parameters.  When I use the same code for vsphere it creates without any problems. The same result via API, it's looks like a problem with API or sdk

`
data "vra_cloud_account_vmc" "vmc" {
  name = var.cloud_account_name_vmc
}

data "vra_region" "vmc" {
  depends_on       = [data.vra_cloud_account_vmc.vmc]
  cloud_account_id = data.vra_cloud_account_vmc.vmc.id
  region           = data.vra_cloud_account_vmc.vmc.regions[0]
}

resource "vra_flavor_profile" "this" {
  depends_on = [data.vra_region.vmc]
  name       = var.name
  region_id  = data.vra_region.vmc.id

"flavor_mapping" {
     name      = flavor_mapping.value.name
      cpu_count = flavor_mapping.value.cpu_count
      memory    = flavor_mapping.value.memoryInMB
    }
`

**Comment by dmettem** [comment]
@vvinnich This is being looked at and I will get back to you soon.

**Comment by vvinnich** [comment]
@dmettem do you need any additional info or it's known issue?

**Comment by vvinnich** [comment]
I've opened SR for CAS  and support engineer said that This is  known issue with the VMC IAAS-API and is being worked in the backend to be fixed) So I think it's not terraform issue

**Comment by dmettem** [comment]
Yes @vvinnich. I'm aware of the SR and has been in contact with the team handling the issue. It is not provider specific, but an issue in the IaaS API.
