### ISSUE TITLE
adding cloud assembly Integration resources

### ISSUE THREAD

**Issue by vvinnich** [vmware/terraform-provider-vra#176]
Are there plans in roadmap for creating resources for integrating with services like "Gitlab" or "IPAM" etc?

**Comment by dmettem** [comment]
@vvinnich Are there specific integration endpoints you are looking for managing from terraform provider?

**Comment by vrabbi** [comment]
I would be looking for mostly ansible, adding a k8s cluster, git integration and most importantly assigning a git repo and branch to a project

**Comment by vvinnich** [comment]
> @vvinnich Are there specific integration endpoints you are looking for managing from terraform provider?
1. Gitlab
2. IPAM (as example Infoblox)
3. vRO
4. Exntensibility Actions On prem

**Comment by ksoul78** [comment]
**vRA version** : 8.2

Hello

I'm adding a comment to join the need that was exposed to manage integrations with vra provider 

1. IPAM
1. Ansible Tower
2. Gitlab
3. vROPS

Regards,

**Comment by elipsion** [comment]
I'd like to chime in a usage of the `activedirectory` integration. It's highly convenient to have servers added and removed from the AD by vRA.

`POST /provisioning/uerp/provisioning/activedirectory/api/providers`
``` json
{
        "id":"",
        "integrationId":"${integrationId}",
        "projectId": "${projectId}",
        "integrationType":"activedirectory",
        "properties":{
            "ou":"OU=Common Servers",
            "defaultOU":"DC=example,DC=com"
        },
        "tags":[        
        ]
 }
```

**Comment by VickyWinner** [comment]
Hi, I see this is still open.  Does it mean someone already working on to include this.  I see that all CRUD operations are now available per [swagger](https://www.mgmt.cloud.vmware.com/iaas/api/swagger/ui/#/).  I am looking for GitHub & vRO.

**Comment by tenthirtyam** [comment]
Before any integration addition can proceed, the API references for integrations would need to be added to `vra-go-sdk` first.

Ryan

**Comment by tenthirtyam** [comment]
I also suggest that anyone that requires this enhancement add a 👍🏻 as a +1 - it helps the maintainers and product managers gain insight into level of priority.

Ryan

**Comment by mdittbrenner215** [comment]
We were just talking about scripting this out but if we could have it in TF it would be very helpful

**Comment by frodenas** [comment]
I've added a few [examples](https://github.com/vmware/terraform-provider-vra/tree/main/examples/integration) on how to create `Active Directory`, `GitHub`, and `SaltStack` integrations.
