### ISSUE TITLE
vra_fabric_network for nsx-t networks

### ISSUE THREAD

**Issue by vrabbi** [vmware/terraform-provider-vra#178]
how can i filter for nsx-t network? as the network is reported back from the vcenter as a network as well the results are larger than one and therefore it does not work. i have tried filtering on cloudAccountId but that doesnt work either.

bellow are a few of the tests i have done:

data "vra_fabric_network" "vlan77" {
  filter = "name eq 'ls_vlan_77'"
}
*** this returns more than 1 network so it fails if i remove the vsphere cloud account from vra this indeed works as there is only one network with that name being reported. it seems there is a filter issue with any parameter except for name

data "vra_fabric_network" "vlan77" {
  filter = "id eq 'xxx-xxx-xxx-xxx-xxx'"
}
*** dosent find the network even though the id is correct (pulled from rest api directly)

data "vra_fabric_network" "vlan77" {
  filter = "name eq 'ls_vlan_77 and external_id eq 'xxx-xxx-xxx-xxx-xxx'"
}
*** this returns no networks - when i removed vsphere cloud account and ran with filter just by name this external id is correct and is part of the object as seen through terrafrom console

data "vra_fabric_network" "vlan77" {
  filter = "name eq 'ls_scot_172.77.0.0/16' and cloudAccountId eq 'xxx-xxx-xxx-xxx-xxx'"
}
*** this returns no networks even though this is the correct cloud account id

**Comment by vrabbi** [comment]
any ideas how to tackle this?

**Comment by dmettem** [comment]
@vrabbi I will give it a try and get back.

**Comment by dmettem** [comment]
@vrabbi - I noticed that this issue is due to how vRA IaaS API is handling the already encoded URLs in 8.1. I didn't see the similar behavior with vRA Cloud.

I created an internal issue (17703) and will keep you posted on the timelines as soon as I've more details.

**Comment by vrabbi** [comment]
it seems a workaround is to use tag filters. if i tag the nsx-t network in vra then i can find based on name and tags. this is not optimal but at least allows proceeding with using nsx-t networks via the terraform provider in the meantime until the API is fixed

**Comment by dmettem** [comment]
This issue is fixed in vRA and is included in 8.1 patch 2.
