### ISSUE TITLE
shared_resources option cause project creation to fail

### ISSUE THREAD

**Issue by thecloudxpert** [vmware/terraform-provider-vra#186]
Everytime I declare shared_resources = true, within the code block for vra_project, as per the given example, i get the following error:

Error: Unsupported argument

  on prod.projects.tf line 24, in resource "vra_project" "TF_demo":
  24:   shared_resources = false

An argument named "shared_resources" is not expected here.

**Comment by markpeek** [comment]
Are you using the latest release [v0.1.9](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.9) which was released yesterday?

**Comment by thecloudxpert** [comment]
no i wasn't - the syntax is now working but there is another issue i'll raise it separately
