### ISSUE TITLE
shared_resources value doesn't change when set to false.

### ISSUE THREAD

**Issue by thecloudxpert** [vmware/terraform-provider-vra#187]
Firstly, I am assuming that the shared_resources attribute is to toggle the "Deployments are shared between all users in the project" toggle.

If i have that toggle to disabled in the gui and run the shared_resources = true, then the toggle is switched to enabled.

When i have the toggle to enabled and try to disable it, nothing happens even though the terraform apply suggests a change as a occurred. I tried to refresh the browser but still no change.

**Comment by dmettem** [comment]
Thanks for the issue. I ran into the issue yesterday and it is due to how the SDK is generated as the optional boolean properties set to false are omitted before API requests are sent out of the provider.

**Comment by dmettem** [comment]
Fixed in #189. Next release will have this change.

**Comment by dmettem** [comment]
Closed via #189.
