### ISSUE TITLE
Support of Compute resource

### ISSUE THREAD

**Issue by bserratrice** [vmware/terraform-provider-vra#196]
When creating a Cloud Zone leveraging vSphere Cloud Account, it is needed to be able specify what Compute we allow provisioning to.
The way it is done is through tagging on the Compute resource.

**Comment by dmettem** [comment]
@bserratrice Are you asking about tagsToMatch in the cloud zone? If so, cloud zone resource already supports it. If not, can you elaborate the ask please?

**Comment by dmettem** [comment]
Looking at the issue again, I think ask here is to allow adding tags to fabric computes that are part of a region. I'm marking this as enhancement and will get back on the timelines.

**Comment by ksoul78** [comment]
Hello @dmettem , 

I found this enhancement request that match with our need to add tags to fabric compute juste like you said previously. 

We managed to configure tags on  fabric network through vra_fabric_network_vsphere resource that allow to import content to terraform. 

Do you plan to work on this request soon?

Thanks.
