### ISSUE TITLE
 Terraform provider reports successful resize even when user does not have permission to perform the resize

### ISSUE THREAD

**Issue by foshea** [vmware/terraform-provider-vra#197]
vRA Terraform provider reports successfully resize even when the user does not have permission to perform the resize operation.

The day 2 activity is disabled but the plan reports the change completed

Plan: 0 to add, 1 to change, 0 to destroy.
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

The VM is not resized in vRA, which is correct - but provider does not recognize this.

**Comment by dmettem** [comment]
Thanks @foshea for reporting! Please provide the following details:

1. vRA Cloud/on-prem. If on-prem, what is the vRA version.
2. Terraform provider version
3. User roles in vRA like Cloud Assembly administrator/member/user or Service Broker administrator/member/user
4. main.tf before the change and the change made

**Comment by foshea** [comment]
hi @dmettem 

1.  vRA 8.0.1 on prem
2. Terraform v0.12.21
3. Service Broker User role.

Same confirmed in vRA 8.1 and provider 0.2.0

below is plan;
only change made is to change inputs.numCores and run terraform apply.

provider "vra" {
url = var.url
refresh_token = var.refresh_token
insecure = var.insecure
}

resource "vra_deployment" "vra_terra" {
name = var.deployment_name
description = "terraform test deployment"

catalog_item_id = var.catalog_item_id
catalog_item_version = var.catalog_item_version
project_id = var.project_id

inputs = {

numCores = var.numCores
memoryInGb = var.memoryInGb
diskSizeInGb = var.diskSizeInGb
sealId = var.sealId
sealDeploymentId = var.sealDeploymentId
costCenter = var.costCenter
siteResolver = var.siteResolver
primaryResolver = var.primaryResolver
supportTeamName = var.supportTeamName
customerContactGroup = var.customerContactGroup
adOperationalResolver = var.adOperationalResolver

}

timeouts {
create = "60m"
delete = "30m"
}

}

output "host_ip" {
value = jsondecode(sort(vra_deployment.vra_terra.resources.*.properties_json)[0]).address
}
output "host_name" {
value = jsondecode(sort(vra_deployment.vra_terra.resources.*.properties_json)[0]).resourceName
}
output "host_status" {
value = vra_deployment.vra_terra.status
}

**Comment by dmettem** [comment]
Thanks @foshea for providing the details!

If a change is recognized in the deployment inputs, the provider performs the `update` day-2 action on the deployment, not the `resize`.
I believe, vRA doesn't allow the `update` day-2 action on deployments requested from a catalog item, but. only on those requested from blueprints. I'll confirm this once I validate.

If `update` action is not available on a deployment, the provider should display an error. I'll check this and get back.

**Comment by dmettem** [comment]
Using `terraform import`, I imported an existing deployment that does not have the _Update_ action available in UI. Once the import is successful, I added/changed the inputs in the config file to trigger the _Update_ action.

Upon running `terraform apply`, I got:

> vra_deployment.this: Modifying... [id=2f8ad6a4-6c38-4a39-baa9-513baa76b27f]
>
> Error: noticed changes to inputs, but 'Update' action is not supported based on the current state of the deployment

@foshea Based on your last [comment](https://github.com/vmware/terraform-provider-vra/issues/197#issuecomment-628097024), if the change is only made to " _inputs.numCores_", it is same as requesting the "Update" day-2 action in the UI.

Hope this helps. Please share the log if you need further assistance.

**Comment by dmettem** [comment]
If the `Update` action is not available on a deployment, and if there are changes noticed to `vra_deployment` inputs in the configuration file, instead of just logging the debug statement, `terraform apply` command is now failed with the following error:

> noticed changes to inputs. but 'Update' action is not supported based on the current state of the deployment
