### ISSUE TITLE
RPC Crash when running terraform apply with changes

### ISSUE THREAD

**Issue by vrabbi** [vmware/terraform-provider-vra#202]
**vRA version**
VRA 8.1
**Terraform version**
Terraform v0.12.24
**terraform-provider-vra plugin version**
v0.2.0

**Describe the bug**
I have a main.tf that provisions a new deployment and then a vra machine and a load balancer. the deploy succeeds but any terraform plan/apply after the resources have been provisioned fails with an rpc error.

**To Reproduce**
1. apply the main tf and once complete try to do a terraform plan/apply again and it fails.
*** Main.tf file ***
provider "vra" {
  url           = "https://demo-vra.domain.local"
  refresh_token = "TOKEN VALUE"
  insecure      = true
}

data "vra_project" "prj_demo" {
  name = "prj_demo"
}

data "vra_network" "vlan76" {
  name = "NET76"
  tags {
    key   = "networktype"
    value = "public"
  }
}

resource "vra_deployment" "ocp_cluster" {
  name          = "cls9ocp"
  project_id    = data.vra_project.prj_demo.id
}

variable "props" {
  type = map(string)
  default = {
    "ovf.prop:hostname" = "ovf.prop:scott-ovf-test-09-tf"
    "ovf.prop:instance-id" = "ovf.prop:id-ovf"
    "ovf.prop:password" = "ovf.prop:PASSWORDVALUE"
    "ovf.prop:public-keys" = "ovf.prop:SSH KEY VALUE"
  }
}
resource "vra_machine" "machine1" {
  name        = "tf-machine-09"
  description = "terrafrom test machine"
  project_id  = data.vra_project.prj_demo.id
  image       = "test"
  flavor      = "medium"
  deployment_id = vra_deployment.ocp_cluster.id
  custom_properties = var.props
  tags {
    key   = "ocpCluster"
    value = vra_deployment.ocp_cluster.name
  }
  nics {
    network_id = data.vra_network.vlan76.id
  }
  timeouts {
    create = "60m"
    delete = "20m"
  }
}

resource "vra_load_balancer" "ocp_lb" {
  name = "test lb"
  project_id = data.vra_project.prj_demo.id
  deployment_id = vra_deployment.ocp_cluster.id
  nics {
    network_id = data.vra_network.vlan76.id
  }
  custom_properties = {
    edgeClusterRouterStateLink = "/resources/routers/e102c442-b0c0-449d-abc6-c9098463b73b"
    tier0LogicalRouterStateLink = "/resources/routers/0af2d063-9279-4e7a-8d25-f7113d648686"
  }
  routes {
    member_port = 80
    member_protocol = "TCP"
    port = 80
    protocol = "TCP"
  }
  targets {
    machine_id = vra_machine.machine1.id
    network_interface_id = split("network-interfaces/",element(tolist(vra_machine.machine1.links),2).hrefs[0])[1]
  }
}

**Expected behavior**
The expected behavior would be the ability to run an apply / plan allowing for changes

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log
[tracelog.txt](https://github.com/vmware/terraform-provider-vra/files/4626694/tracelog.txt)
3. crash.log(if any)
[crashlog.txt](https://github.com/vmware/terraform-provider-vra/files/4626696/crashlog.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.0.4

**Comment by dmettem** [comment]
Issue is fixed in #204. It will be included in next release.
