### ISSUE TITLE
unknown status UPDATE_SUCCESSFUL

### ISSUE THREAD

**Issue by bortek** [vmware/terraform-provider-vra#203]
**vRA version**
The vRA Cloud vRealize Automation 8.1.0.9326 (15986821)
**Terraform version**
v0.12.23
**terraform-provider-vra plugin version**
0.2.0

**Describe the bug**
Just upgraded to the latest 0.2.0 provider and terraform apply fails when creating VMs while in VRA the nodes are created successfully. 

Is there some mapping of error codes missing either in VRA or in provider?

**To Reproduce**
N/A

**Expected behavior**
it should not fail but should print success

**Screenshots**
N/A

**Logs**
2020-05-14T13:23:19.587Z [DEBUG] plugin.terraform-provider-vra: 2020/05/14 13:23:19 

2020/05/14 13:23:19 [DEBUG] vra_deployment.master[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: deploymentCreateStatusRefreshFunc: unknown status UPDATE_SUCCESSFUL

2020/05/14 13:23:19 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: deploymentCreateStatusRefreshFunc: unknown status UPDATE_SUCCESSFUL

2020/05/14 13:23:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: deploymentCreateStatusRefreshFunc: unknown status UPDATE_SUCCESSFUL

Error: deploymentCreateStatusRefreshFunc: unknown status UPDATE_SUCCESSFUL

  on main.tf line 19, in resource "vra_deployment" "bootstrap-0":

  19: resource "vra_deployment" "bootstrap-0" {

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by dmettem** [comment]
@bortek - I'm curious to see the deployment status `UPDATE_SUCCESSFUL` during creation of deployment. Please provide the config file snippet/example that returned UPDATE_SUCCESSFUL during create.

Currently, the `deploymentCreateStatusRefreshFunc` expects only `CREATE_*` statuses. I've made the change to include `UPDATE_*` statuses also to be valid ones.

Fix is included in PR #201.

**Comment by bortek** [comment]
I cannot see it myself in VRA. I need to ask @magnusstrandberg1 to check it for you.

**Comment by bortek** [comment]
Since I wanted to test how change you made to UPDATE_SUCCESSFUL works I have compiled the vra provider from the master branch and tested it. To my surprise I have not seen UPDATE_SUCCESSFUL failure anymore and note even that status in the terraform apply logs. 

Was it PR201 that made this effect?

**Comment by dmettem** [comment]
Yes @bortek. #201 included the fix for this issue as well.

**Comment by bortek** [comment]
Well done then! When are you planning to make a next release?

**Comment by dmettem** [comment]
Version 0.2.1 is released already that  includes this fix.
https://github.com/vmware/terraform-provider-vra/releases/tag/v0.2.1
