### ISSUE TITLE
Request Deployment with array as input

### ISSUE THREAD

**Issue by adielgilboa** [vmware/terraform-provider-vra#205]
**vRA version**
8.1
**Terraform version**
Terraform v0.12.25
**terraform-provider-vra plugin version**
provider.vra v0.2.0

**Describe the bug**
When trying to apply terraform config for deploying a blueprint which has an input of type array of strings terraform fails. 
based on the go code for input schema on resource_deployment, it looks like it expects only strings.

**To Reproduce**
1- create a blueprint that receives an input of array of strings 
2- create terraform files to request the deployment from the blueprint  
3- terraform plan fails with the error "string required"

**Expected behavior**
run smoothly :D

**Comment by dmettem** [comment]
@adielgilboa Share the config file or snippet that shows how the inputs are provided in the tf config file. Also share the debug/trace log.

**Comment by adielgilboa** [comment]
Hi Deepak,
Please find the files below. this also contains the BP version specified at the tfvars (with an array input) :
[terraform.zip](https://github.com/vmware/terraform-provider-vra/files/4662897/terraform.zip)

Thanks :)

**Comment by dmettem** [comment]
Thanks @adielgilboa!

**Comment by vrabbi** [comment]
Any updates on this? I am having the same issue

**Comment by dmettem** [comment]
I'm working on the fix and will soon update here with an ETA. Thanks for the patience.

**Comment by rlabinot** [comment]
Hello,

Just a comment to say that I also have the same problem with an input for the disk size that I want to update from terraform.

```
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: -----------------------------------------------------
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 HTTP/1.1 400 Bad Request
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 Content-Length: 112
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 Cache-Control: no-cache, no-store, max-age=0, must-revalidate
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 Content-Type: application/json
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 Date: Fri, 10 Jul 2020 12:29:57 GMT
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 Expires: 0
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 Pragma: no-cache
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 Strict-Transport-Security: max-age=31536000 ; includeSubDomains
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 X-Content-Type-Options: nosniff
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 X-Frame-Options: DENY
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 X-Xss-Protection: 1; mode=block
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58 {"message":"Invalid inputs: diskSize: Expected type NUMBER but was STRING..","statusCode":400,"errorCode":20021}
2020-07-10T14:29:58.452+0200 [DEBUG] plugin.terraform-provider-vra_v0.2.2.exe: 2020/07/10 14:29:58
2020/07/10 14:29:58 [DEBUG] vra_deployment.this: apply errored, but we're indicating that via the Error pointer rather than returning it: unknown error (status 400): {resp:0xc000385320}
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/07/10 14:29:58 [TRACE] EvalWriteState: recording 0 dependencies for vra_deployment.this
2020/07/10 14:29:58 [TRACE] EvalWriteState: writing current state object for vra_deployment.this
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/07/10 14:29:58 [TRACE] EvalApplyProvisioners: vra_deployment.this is not freshly-created, so no provisioning is required
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/07/10 14:29:58 [TRACE] EvalWriteState: recording 0 dependencies for vra_deployment.this
2020/07/10 14:29:58 [TRACE] EvalWriteState: writing current state object for vra_deployment.this
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalIf
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalIf
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/07/10 14:29:58 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/07/10 14:29:58 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: unknown error (status 400): {resp:0xc000385320}
2020/07/10 14:29:58 [ERROR] <root>: eval: *terraform.EvalSequence, err: unknown error (status 400): {resp:0xc000385320}
2020/07/10 14:29:58 [TRACE] [walkApply] Exiting eval tree: vra_deployment.this
2020/07/10 14:29:58 [TRACE] vertex "vra_deployment.this": visit complete
2020/07/10 14:29:58 [TRACE] dag/walk: upstream of "provider.vra (close)" errored, so skipping
2020/07/10 14:29:58 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/07/10 14:29:58 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/07/10 14:29:58 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2020/07/10 14:29:58 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2020/07/10 14:29:58 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/07/10 14:29:58 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info

Error: unknown error (status 400): {resp:0xc000385320}

  on main.tf line 16, in resource "vra_deployment" "this":
  16: resource "vra_deployment" "this" {

2020/07/10 14:29:58 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
```

On my terraform code, the input "diskSize" is a number but it seems that terraform always passes inputs as string.

**Comment by dmettem** [comment]
It took awhile for me to get back on this issue. Here's the latest update:

At present, `inputs` in `vra_deployment` resource is of type `TypeMap` with Elements of type `TypeString` for values. Hence all the elements in the `inputs` are expected to be Strings for both keys and values. However, the inputs of primitive type (`integer`, `boolean`, and `string`) are auto converted to `string` by TF.

@rlabinot - If you want the diskSize to work, you may change your blueprint to have diskSize input to type `integer` instead of `number`.

I'm working on to add the support for other input types supported in vRA blueprints i.e. NUMBER, ARRAY, and OBJECT. However, TF still enforces that these values are provided as strings in the configuration file as `inputs` is of type `TypeMap`. This is a limitation from TF plugin SDK.

To get past this limitation until it is fixed in SDK, the values should be defined as follows in TF configuration file.

```
inputs = {
    stringInput  = "small"
    integerInput = 1
    booleanInput = false
    numberInput  = 10.5
    arrayInput   = <<-EOT
    ["foo", "bar"]
    EOT
    objectInput  = <<-EOT
    { "key1": "value1" }
    EOT
  }
```

I notice one downside with providing the Array and Object Inputs as String i.e. when the latest deployment state is read from remote and updated into local state file, they are not strings anymore. This is how the above inputs look in the state file.
```
inputs = {
    stringInput  = "small"
    integerInput = 1
    booleanInput = false
    numberInput  = 10.5
    arrayInput   = [foo bar]
    objectInput  = map(key1:value1)
  }
```
This causes the plan to show differences in inputs of type array and object even though there are no user-made changes which is a little inconvenient. Only way to overcome this is to not update the inputs received from remote service in the `inputs` argument, but only update the `inputs_including_defaults` attribute.

Here're the two options I see:
1. Continue to update `inputs` argument with data received from remote service. This impacts only those configurations with array and object type inputs with incorrect plan even when there are no-user made changes.

2. On Read, stop to update `inputs` argument with inputs received from remote service, but only update `inputs_including_defaults` attribute. This impacts the local state file as it doesn't show the inputs changed in vRA directly in `inputs` argument anymore. Users would have to refer to `inputs_including_defaults` for the latest inputs provided to reach the current state of deployment.

I'm planning to go with option 2 and keep the `inputs` in state file consistent with user-provided inputs in TF configuration file and `inputs_including_defaults` in state file consistent with inputs received from deployment API.

**Comment by vrabbi** [comment]
Now that in the new version of the sdk I believe you can add lists and other obects to a map (that's what I was told haven't verified yet) which should be available with tf 0.13 can we expect this to be possible to implement in the near future without a workaround like mentioned above? If so maybe it's worth waiting for the new sdk and tf version and make the provider dependent on the new tf version?

**Comment by dmettem** [comment]
I think the latest version of SDK (v1.15.0) supports providing `Elem` of non primitive types thus by supporting lists, etc. in a map, however when I remove the `Elem` from schema for `inputs` attribute, TF still complains that `string` required.

I haven't played with TF 0.13 Beta yet. I haven't tested with TF 0.13 Beta yet. If it supports list and map objects as values for `TypeMap` attribute keys, then the vRA provider can resume to update the `inputs` even if option 2 from my previous comment is implemented as temporary workaround. 

If option 2 is implemented, this is how the `inputs` and `inputs_including_defaults` will appear in the `terraform show` output. And if the deployment is updated directly in vRA with a newer set of inputs, those changes will only appear in `inputs_including_defaults`. And `terraform plan` shows changes in inputs only if they are made by the user.
```
inputs = {
        "arrayInput"  = jsonencode(
            [
                "foo",
                "bar",
            ]
        )
        "booleanInput" = "false"
        "integerInput" = "1"
        "numberInput" = "11.1"
        "objectProp" = jsonencode(
            {
                key1 = "value1"
            }
        )
        "stringInput" = "small"

    }
inputs_including_defaults = {
        "arrayInput"  = "[foo bar]"
        "booleanInput" = "false"
        "integerInput" = "1"
        "numberInput" = "11.1"
        "objectInput" = "map[key1:value1]"
        "stringInput" = "small"
    }
```

Plan when changes are made to inputs:
```
~ inputs                    = {
          ~ "arrayInput"  = jsonencode(
              ~ [
                    "foo",
                    "bar",
                  + "baz",
                ]
            )
            "booleanInput"      = "false"
            "integerInput"       = "1"
            "numberInput"     = "11.1"
          ~ "objectInput" = jsonencode(
              ~ {
                  + key  = "value"
                  - key1 = "value1" -> null
                }
            )
            "stringInput" = "small"
        }
```

Suggestions? I'll also look into testing this with TF 0.13 Beta meanwhile.

**Comment by vrabbi** [comment]
Im sure you have already thought about this and my guess is there is too big of an implication to making this change but has it been discussed about possibly moving the elem to typeset which isn't bound to the same constraints as typemap? I know type set has drawbacks but not sure if it could provide a solution here. Another option is to have the user place the input in a formated string that the provider would parse backend to a list. I have seen this done before in other providers where a delimeter is set and then the user simply joins there list using the delimeter.
My worry about solution 2 ( which is great for many use cases and would be great improvement ) is that changes made to inputs via vra are disregarded by terrafrom plan is I understand correctly which is an issue as then it is not completely doing desired state.

**Comment by dmettem** [comment]
I understand and agree with you about the concern with solution 2.

The option you mentioned for formatting the list with a delimiter may work only for inputs of type Array with elements of primitive type. But they get complex for inputs of type Object, or even Array of Objects (something like those in #216).

I've considered about changing `inputs` to `TypeSet` (`TypeList` with `MaxItems: 1`), but TF complains that `Elem` should be set for lists. If I set the `Elem` inside `inputs` to a schema of `key` and `value` attributes, where key is the input name and value for the input value, the problem arises again with type for `value` attribute, which is, users should provide the inputs of type Array and Objects as strings in configuration file. And when persisted to state file, I'm not quite sure if there would be issue with `plan` command as in solution 2. Moreover this would be a breaking change for all the existing configurations.
I'll play around to see what would it take to convert the `inputs` to `TypeSet` from `TypeMap` and the full set of implications.

**Comment by markpeek** [comment]
I will note that upgrading to terraform-plugin-sdk v2.0 is a [breaking change](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/CHANGELOG.md#200-rc1-may-05-2020) for terraform v0.11 and earlier. Might want to see thumbs up (v0.12+) or thumbs down (v0.11 and earlier) on this comment to understand what users are using now.

**Comment by A-Joshi** [comment]
We are on Terraform 0.13.2 because of the count and for-each capability in modules amongst other stuff.

**Comment by hkamat** [comment]
I have a similar issue though with using catalog item.
Running a deployment with catalog item which requires an array it gives error Array
89:     inputs = {
  90:     action                        = "Accept"
  91:     edgeName                  = "xxxxxxxxx"
  92:     ruleName                  = "Test_sshaccesssource"
  93:     sourceType                = "Any"
  94:     serviceNames          = ["SSH"]
  95:     enableLogging         = "true"
  96:     destinationType               = "IP Set"
  97:     destIpSetIpaddresses    = var.ip
  98:     destinationIpSetName  = "Test_IPSet_Payload"
  99:     sourceIpSetIpaddresses  = ""
 100:     }

Inappropriate value for attribute "inputs": element "serviceNames": string
required.

After i do the workaround suggested i get below error
Error: [POST /catalog/api/items/{id}/request][400] requestCatalogItemUsingPOSTBadRequest  &{Message:serviceNames: Expected type ARRAY but was STRING. StatusCode:400}

Is there any fix for this?

**Comment by hobovirtual** [comment]
looking for the same functionality 

blueprint has an array of object

thanks!

**Comment by dmettem** [comment]
I'm going to try this out with terraform-plugin-sdk 2.0.x which will break the support for terraform 0.11 or lower.

Based on https://github.com/hashicorp/terraform-plugin-sdk/blob/8dec4902fc67e60ecaa466261cbe892a09a5208e/helper/schema/schema.go#L1830, map values are still validated to primitive types.

I'll post an update this week as I resume the work on this issue.

**Comment by dmettem** [comment]
I've opened a PR #259 with a fix that I tested to a certain extent with inputs of type array and object.

Even though I first fixed the issue after upgrading the provider to use terraform-plugin-sdk v2.0.4, there are still limitations from v2 sdk, due to which I made the same fix while using v1 SDK and opened it for review.

If anyone happens to try this fix before releasing the next version, share the results here. Thanks!

**Comment by A-Joshi** [comment]
Thanks - will try once there is a build with the new commit.

**Comment by hobovirtual** [comment]
thanks @dmettem this is working as expecting with 0.3.3 provider!
great work!

**Comment by dmettem** [comment]
@hobovirtual - Thanks for confirming!

**Comment by A-Joshi** [comment]
Seems to be working - now to debug the actual blueprints!
