### ISSUE TITLE
Add On-Boarding Plan Resource and Datasource

### ISSUE THREAD

**Issue by vrabbi** [vmware/terraform-provider-vra#206]
vRA version
8.1
terraform-provider-vra plugin version
0.2.0

**Is your feature request related to a problem? Please describe.**
do to limitations with VRA in terms of customability at deployment time we need to provision the VMs directly through vCenter but also want to manage them via VRA. we also are a brownfield environment so on-boarding is a great capability of the product

**Describe the solution you'd like**
addition of Data Source and Resource for creating and managing an On Boarding plan

**Describe alternatives you've considered**
beyond this it would require doing direct API calls to the VRA utilizing possibly null_resource with local exec to run API calls but that seems like a bad idea. this would be a great capability to have in the provider

**Additional context**
based on what i can tell this is not in the VRA GO SDK as of yet but i may have missed it

**Comment by dmettem** [comment]
Hi @vrabbi,

I'll work internally and get back to you soon on the feasibility and plans to support this thru TF provider. Thanks!

**Comment by vrabbi** [comment]
Any updates on this being added or not in the future?

**Comment by dmettem** [comment]
This is being added to the roadmap for future releases.

**Comment by vrabbi** [comment]
Any time frame on this being added?
