### ISSUE TITLE
Support for First Class Disks 

### ISSUE THREAD

**Issue by sbadem** [vmware/terraform-provider-vra#208]
We would like to add support for vSphere First Class Disks for our Terraform Provider
Here are the use cases we need to support:

CREATE
Creating FCDs
Promote an existing virtual disk into FCD
Clone an existing FCD
Linked Clone from an existing FCD Snapshot. 
SNAPSHOT
Create Snapshot
Delete Snapshot
Revert Snapshot
BACKUP/RESTORE
Backup and Restore FCDs
DELETE
Deleting FCDs
DISCOVER
Discovering/ Importing FCDs

DAY2
Extend the size of an FCD
Rename an FCD
Updating the SPBM policy associated with an FCD
Convert an FCD from thin provisioned to thick provisioned
Attaching a tag to an FCD.
Migrating an FCD to another datastore

**Comment by vrabbi** [comment]
This doesn't exist in vra yet.

**Comment by vrabbi** [comment]
Now that this exists in vra 8.2 is this planned to be added to the provider?

**Comment by dmettem** [comment]
This has been fixed and released in [v.0.3.3](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.3.3).
