### ISSUE TITLE
project resource options

### ISSUE THREAD

**Issue by vrabbi** [vmware/terraform-provider-vra#211]
**Is your feature request related to a problem? Please describe.**
Not all features available to configure on a project are available via the terraform provider

**Describe the solution you'd like**
added support for viewers role which was added in 8.1
added support for defining custom properties on a project

**Describe alternatives you've considered**
no alternatives exist within terraform. currently this is done manually but could be automated via api

**Additional context**
The viewers role is a huge addition in the latest release of vra and should be added in the provider. also having the ability to configure custom properties is a big deal in regards to fully automated configs of vra where custom properties are integral to many automations

**Comment by dmettem** [comment]
Hi @vrabbi, 

I've created an internal ticket to add support for custom properties in Projects API. Once it is available, TF provider will add the support to it.

Meanwhile, I will work on adding support for Viewers in TF provider as the API supports it already.

Thanks!
