### ISSUE TITLE
Add the vra provider to the terrafrom provider registry ahead of version 0.13

### ISSUE THREAD

**Issue by vrabbi** [vmware/terraform-provider-vra#214]
Now that 0.13 beta is out which allows for third party providers to be added to the terrafrom registry and be pulled automatically at terrafrom init it would be great to have this setup for this provider at least until this becomes an official provider

**Comment by dmettem** [comment]
Provider certification is already on the roadmap and will be picked up soon.
It is being discussed internally if this may be the first step towards the certification.
We will update the issue soon once the prioritization is complete. Thanks!

**Comment by vrabbi** [comment]
@dmettem any updates on this now that 0.13 is GA?

**Comment by moffzilla** [comment]
any available workaround instructions for making this provider available for 0.13.00? ( I could open an independent issue if makes more sense but currently experiencing: 

Initializing provider plugins...
- Finding latest version of hashicorp/vra...

Error: Failed to query available provider packages

**Comment by vrabbi** [comment]
@moffzilla you could get it to work by following the official docs of hashicorp in regards to »In-house Providers that are not hosted on a registry found at the following link:
https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers

**Comment by markpeek** [comment]
We're coming up to speed on the changes needed to publish this out for 0.13 and will look to get it done "soon".

**Comment by vrabbi** [comment]
I see it was added 4 days ago! Great to see this move.
