### ISSUE TITLE
Question regarding tests/test infra. (network_ip_range issue) 

### ISSUE THREAD

**Issue by cars** [vmware/terraform-provider-vra#223]
@dmettem @Prativa20 @markpeek question for y'all. I've been working on adding a resource for internal network_ip_ranges. As I look at writing the tests I run into a bit of a dilemma as adding a ip_range to a fabric network requires knowing the CIDR information for that fabric network since the ip range has to fall within that network. So I'm wondering if it's possible to make assumptions about the test infrastructure y'all use or if you might have an suggestions about how you'd like me to proceed/handle this? 

-CRT

**Comment by dmettem** [comment]
@cars - If the resource/data source has a required attribute that is dependent on the test infrastructure, you can define them as reading from environment variables. Refer to [provider_test.go](https://github.com/vmware/terraform-provider-vra/blob/master/vra/provider_test.go) for reference.

**Comment by cars** [comment]
@dmettem Thanks I'd forgotten about that...
