### ISSUE TITLE
Cannot unzip .zip provider file for linux starting 0.3.0 usin tar

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#232]
**vRA version**
vRA8
**Terraform version**
0.13
**terraform-provider-vra plugin version**
https://github.com/vmware/terraform-provider-vra/releases/tag/v0.3.1

**Describe the bug**
     When I download the latest version of provider,  I see the file for linux has changed from `.tgz` to `.zip` and when I use tar to unzip, I am getting error below

```
17:23:54  + tar xvf terraform-provider-vra_0.3.1_linux_amd64.zip
17:23:54  tar: This does not look like a tar archive
17:23:54  tar: Skipping to next header
17:23:54  tar: Exiting with failure status due to previous errors
```

**To Reproduce**
1. download latest provider for linux from https://github.com/vmware/terraform-provider-vra/releases/download/v0.3.1/terraform-provider-vra_0.3.1_linux_amd64.zip
2. unzip by typing `tar xvf terraform-provider-vra_0.3.1_linux_amd64.zip`
3. You get the error as mentioned above

**Expected behavior**
Should unzip the file.

**Screenshots**
N/A

**Logs**
Attach logs to help debug the issue
N/A

**Desktop (please complete the following information):**
 - OS: RedHat Linux

**Additional context**

**Comment by dmettem** [comment]
With Terraform 0.13, you can run `terraform 0.13upgrade` first to update the module/workspace. Once this is successful, you can run `terraform init` that directly downloads the plugin instead of having to manually download the binary from GitHub.

**Comment by VickyWinner** [comment]
@dmettem,  Looks like VMWare just published it in the [verified ](https://registry.terraform.io/providers/vmware/vra/latest) category.  Will update my scripts so I don't have to download as third party anymore.  I am closing this issue now.  Thanks.

**Comment by VickyWinner** [comment]
@dmettem.  I am able to verify this. This issue can be closed now.  Thanks.

**Comment by markpeek** [comment]
While the provider will now download directly, I wanted to document the solution to the original issue. The original poster was using `tar` to unpack the `.zip` file. The correct utility would be `unzip`.
```
$ uname -a
Linux markpeek-ubuntu 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ curl -OL  https://github.com/vmware/terraform-provider-vra/releases/download/v0.3.1/terraform-provider-vra_0.3.1_linux_amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   670  100   670    0     0   1892      0 --:--:-- --:--:-- --:--:--  1892
100 8300k  100 8300k    0     0  4341k      0  0:00:01  0:00:01 --:--:-- 6080k
$ ls -l terraform-provider-vra_0.3.1_linux_amd64.zip
-rw-rw-r-- 1 markpeek markpeek 8499566 Aug 27 06:47 terraform-provider-vra_0.3.1_linux_amd64.zip
$ file terraform-provider-vra_0.3.1_linux_amd64.zip
terraform-provider-vra_0.3.1_linux_amd64.zip: Zip archive data, at least v2.0 to extract
$ unzip terraform-provider-vra_0.3.1_linux_amd64.zip
Archive:  terraform-provider-vra_0.3.1_linux_amd64.zip
  inflating: LICENSE
  inflating: README.md
  inflating: terraform-provider-vra_v0.3.1
$ ls
LICENSE    terraform-provider-vra_0.3.1_linux_amd64.zip
README.md  terraform-provider-vra_v0.3.1
$ file terraform-provider-vra_v0.3.1
terraform-provider-vra_v0.3.1: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=y-mnxPnuzijq4Bm64XL5/-o-Hh5tpIEetxx9ga0Sz/TgAgQBjz3TRn3VLoyUe6/HJFQnl9Un0zbtY5__Xaw, stripped
```
