### ISSUE TITLE
Faile to create a vSphere Image Mapping

### ISSUE THREAD

**Issue by moffzilla** [vmware/terraform-provider-vra#234]
**vRA version**
Version 8.1.0.9583 (16633378) 
**Terraform version**
Terraform v0.12.29
**terraform-provider-vra plugin version**
+ provider.vra v0.2.4

**Describe the bug**
When attempting to create a single vSphere Image Mapping by "terraform apply -auto-approve" we get error:

**Error: unknown error (status 409): {resp:0xc0001225a0} 
  on main.tf line 13, in resource "vra_image_profile" "this":
  13: resource "vra_image_profile" "this" {**

Doing the "Terraform plan" doesn't return an error.

**To Reproduce**
1. Terraform config file (for updates, config file before applying the change and the change made)

`provider vra {
  url           = var.vra_url
  refresh_token = var.vra_refresh_token
  insecure = true
}

data "vra_region" "this" {
  cloud_account_id = "5ea2b589-dc80-49f9-8c67-66178a8b0f1f"
  region           = "Datacenter:datacenter-21"
}

# Create a new image profile
resource "vra_image_profile" "this" {
  name        = "vsphere-image"
  description = "vSphere image profile created by Terraform"
  region_id   = data.vra_region.this.id

  image_mapping {
    name       = "windows"
    image_name = "win2016bis"
  }
}
`
We collected the "cloud_account_id" from API and it seems aligned to the one seen at the URL when in vRA URL for Cloud Accounts
also "region" value is aligned to what the API call returns in "enabledRegionIds", "image_name" is a valid template displayed when adding the image directly from vRA UI.

2. Terraform command

`# terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vra_region.this: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vra_image_profile.this will be created
  + resource "vra_image_profile" "this" {
      + description = "vSphere image profile created by Terraform"
      + id          = (known after apply)
      + name        = "vsphere-image"
      + region_id   = "c6e082a3-cbe7-4c47-971b-de0c6d93531d"

      + image_mapping {
          + external_id        = (known after apply)
          + external_region_id = (known after apply)
          + image_name         = "win2016bis"
          + name               = "windows"
          + organization       = (known after apply)
          + os_family          = (known after apply)
          + owner              = (known after apply)
          + private            = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------`

Then we try "terraform apply -auto-approve" we get the error

3. Error

`data.vra_region.this: Refreshing state...
vra_image_profile.this: Creating...

Error: unknown error (status 409): {resp:0xc0009dc1b0} 

  on main.tf line 13, in resource "vra_image_profile" "this":
  13: resource "vra_image_profile" "this" {
`
Looking at the vRA Provider logs, the API seems to be complaining that the image profile already exists ( which doesn't ), responding with error:

`2020-08-27T19:50:11.093-0400 [DEBUG] plugin.terraform-provider-vra_v0.2.4: {
2020-08-27T19:50:11.093-0400 [DEBUG] plugin.terraform-provider-vra_v0.2.4:  "message": "Image profile for the same region already exists",
2020-08-27T19:50:11.093-0400 [DEBUG] plugin.terraform-provider-vra_v0.2.4:  "statusCode": 409,
2020-08-27T19:50:11.093-0400 [DEBUG] plugin.terraform-provider-vra_v0.2.4:  "errorCode": 0,
2020-08-27T19:50:11.093-0400 [DEBUG] plugin.terraform-provider-vra_v0.2.4:  "serverErrorId": "3176c4fb-8d9a-4616-96d8-cc95860ace7c",
2020-08-27T19:50:11.093-0400 [DEBUG] plugin.terraform-provider-vra_v0.2.4:  "documentKind": "com:vmware:xenon:common:ServiceErrorResponse"
2020-08-27T19:50:11.093-0400 [DEBUG] plugin.terraform-provider-vra_v0.2.4: }`

**Expected behavior**
Create a vSphere based Image mapping.

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)

**Desktop (please complete the following information):**
 - CentOS Linux release 7.7.1908 (Core)

**Additional context**

**Comment by moffzilla** [comment]
[terraform.log](https://github.com/vmware/terraform-provider-vra/files/5139261/terraform.log)

**Comment by dmettem** [comment]
@moffzilla - The error message `Image profile for the same region already exists` is coming from the product in the API response.

Please provide a screenshot of the Image Profiles in the UI for both the by region name and image mapping name views.

If it's OK with you, please share the response for the following request after replacing the `access_token` and `host_name`  in the request.

> curl --location --request GET 'https://<host_name>/iaas/api/image-profiles?apiVersion=2019-01-15' \
> --header 'Accept: application/json, app/json' \
> --header 'Authorization: Bearer <access_token>'

**Comment by moffzilla** [comment]
@dmettem - Thank you for your response, here's the screenshots and the API response ( JSON )

<img width="1048" alt="Image by Region" src="https://user-images.githubusercontent.com/17936411/91867511-56b1b800-ec39-11ea-9ddb-9f07ca2a1992.png">
<img width="956" alt="Image by name" src="https://user-images.githubusercontent.com/17936411/91867519-59141200-ec39-11ea-81ae-dca28d2107b5.png">

[image-profile-API-Response.zip](https://github.com/vmware/terraform-provider-vra/files/5157011/image-profile-API-Response.zip)

**Comment by dmettem** [comment]
@moffzilla - Thank you for the screenshots and the JSON response. 

As you can see in the screenshot, and notice in the JSON response, there is an image profile already for the `region_id` with which you are trying to create a new image profile.

From the logs, you are trying to create an image profile for the `region_id: c6e082a3-cbe7-4c47-971b-de0c6d93531d`. In the JSON response you shared, you can find an image profile with id `85ed3aa6-6398-485f-a8b5-35e74d0be25c-c6e082a3-cbe7-4c47-971b-de0c6d93531d` with two image mappings named `OAI-Base-Image-1804` and `OAI-Base-Image`.

This explains the error message `Image profile for the same region already exists` and is valid in your environment.

You can run the following request if you would like to see the existing image profile with the region id for which your TF request failed. As before, update the `host_name`, `access_token` and also `region_id` which is `c6e082a3-cbe7-4c47-971b-de0c6d93531d` based on your TF logs.

> curl --location --request GET 'https://<host_name>/iaas/api/image-profiles?$filter=regionId%20eq%20%27<region_id>%27' 
> --header 'Accept: application/json, app/json'
> --header 'Authorization: Bearer <access_token>'

If you would like to add additional image mappings, first you should import this existing image profile under TF management by running `terraform import` and then run `apply` with additional image mappings (including those that are imported into state file).

**Comment by moffzilla** [comment]
So basically, the conflict comes because we’re trying to create a new “image Profile” and  add a new “image mapping” at the same time,
however for the targeted region, there is already an existing “Image Profile” defined, "Moff-vSphere-RegionA01 / RegionA01", hence the API error
Instead of, we just need to define a new “image mapping” only and “import” the existing “image Profile”, so TF can manage it and we could reference for the new image creation
 
I am having some trouble importing the “image Profile” do you have any examples?

**Comment by dmettem** [comment]
There is an issue with import/read functionality of image_profile resource where it is only updating the id of the resource correctly. I'm working on fixing this import/read issue.

You can import image_profile by running `terraform import vra_image_profile.this <id>`. I'll also include an example in my fix.

**Comment by moffzilla** [comment]
I did the Terraform Import for the Image Profile

terraform import vra_image_profile.this 85ed3aa6-6398-485f-a8b5-35e74d0be25c-c6e082a3-cbe7-4c47-971b-de0c6d93531d

Then I was able to create the Image Mappings, by adding the already configured images ( so TF didn't remove ) and a new one as follows:

# Defines existing Image Profile
resource "vra_image_profile" "this" {
  region_id   = "85ed3aa6-6398-485f-a8b5-35e74d0be25c-c6e082a3-cbe7-4c47-971b-de0c6d93531d"
  name        = "Moff-vSphere-RegionA01 / RegionA01"
  description = "vSphere image profile created by Terraform"

  image_mapping {
    name       = "OAI-Windows2016"
    image_name = "win2016bis"
  }

  image_mapping {
    name       = "OAI-Base-Image"
    image_name = "ubuntu1804bis"
  }

  image_mapping {
    name       = "OAI-Base-Image-1804"
    image_name = "ubuntu1804bis"
  }

}

**Comment by dmettem** [comment]
That's good. When you imported the resource, did you see `image_mapping`s and `region_id` pulled into state file for you to reference and add them to TF configuration file?

**Comment by moffzilla** [comment]
I didn't check that but when I did a "terraform show" I was able to see it, and if I inspect the latest, I actually see it there in managed mode

```
  "resources": [
    {
      "mode": "managed",
      "type": "vra_image_profile",
      "name": "this",
      "provider": "provider.vra",
```
