### ISSUE TITLE
Refresh Tokens stored in plain text

### ISSUE THREAD

**Issue by mpuckett159** [vmware/terraform-provider-vra#240]
**vRA version**
vRA 8.x
**Terraform version**
terraform 0.13
**terraform-provider-vra plugin version**
plugin version 0.3.1

**Problem**
I have several concerns regarding the use of refresh tokens and generally how vRealize Automation's on-prem API authentication schema is handled at present. To begin with, all the provider documentation suggests/requires the use of refresh tokens, going so far as to have lines to store these refresh tokens in plaintext in the tfvars files in the example documents. This seems wildly irresponsible to me because refresh tokens live for 6 months, and can not be revoked without disabling the account the token is generated for. This seems like a massive security liability and encourages users of the provider to store sensitive information that will provider anyone with likely administrative access to your environment for up to 6 months, and there is no way for you to easily revoke that access.

**Solutions**
Ideally VMware would resolve this by allowing the generation of API tokens the same way that vRA Cloud allows but seeing as that isn't within the scope of this provider I think some stopgaps can still be implemented to mitigate potential issues and reduce the blast radius of any breaches.

1. Update examples to not include refresh tokens as plaintext variables set in the tfvars files and instead passed in via command line arguments e.g. `terraform apply -var 'refreshToken=fajoweg08923htu9211n'`
2. Allow users to use bearer tokens for on-prem vRA versions to limit account disable times for compromised accounts. This would require just a day rather than 6 months of deactivation
3. Update documentation to reflect that bearer tokens should be preferred when accessing as a user and refresh tokens should only be used with service accounts that can easily be disabled and deleted in the event that they are compromised.

**Comment by cars** [comment]
@mpuckett159  you **_can_** use the bearer/access token instead of the refresh token. For both the refresh and access token it is also possible to set an environment variable VRA_REFRESH_TOKEN or VRA_ACCESS_TOKEN that the provider will use and you can then remove the variable from your tfvars/variables files so it's not recorded anywhere.

I think many of the examples were written before vRA8 on-prem was available and therefore are based on vRA Cloud.

**Comment by mpuckett159** [comment]
Ah ok, this is true. Looks like point 2 can be ignored, but in that case the refresh_token variable name is pretty misleading.

**Comment by dmettem** [comment]
If you want to use access_token instead of refresh_token, you should update the provider block to use the `access_token` argument that uses VRA_ACCESS_TOKEN environment variable.

Refer to https://github.com/vmware/terraform-provider-vra/blob/master/website/docs/index.html.markdown#argument-reference for info on this.

**Comment by cars** [comment]
It's not... if you were passing in the access token as a variable your provider would look like: 
```
provider "vra" {
  # Rely on VRA_URL env variable
  # url           = var.url
  #
   access_token = var.access_token
  insecure = var.insecure // false for vRA Cloud and true for vRA 8.0
}
```

**Comment by mpuckett159** [comment]
Alright either way this doesn't really resolve the documentation issues I have.

**Comment by dmettem** [comment]
Agreed. Will keep the issue open to work on the documentation.

**Comment by mpuckett159** [comment]
Good to hear. Hopefully the larger token issues will be addressed at some point in the product itself and this will all be moot soon. Thanks for looking into it.

**Comment by mpuckett159** [comment]
It may also be beneficial to suggest the use of Vault for more sensitive values like refresh tokens for vRA 8 or long ttl API tokens for vRA Cloud. Just a quick link would probably be enough.

https://learn.hashicorp.com/tutorials/terraform/secrets-vault
