### ISSUE TITLE
Data source for fabric_network to manage more than one result

### ISSUE THREAD

**Issue by hadrouj** [vmware/terraform-provider-vra#241]
vRA version : 8.1
Terraform version : 0.12
terraform-provider-vra : 0.3.1

**Is your feature request related to a problem? Please describe.**
data source for fabric_network expects one result as maximum, which means I have to create as much data source blocks as there are networks in the Network Profile.

**Describe the solution you'd like**
data source should be able to manage more than one results. Here is an example of the solution I would like to see :
```
data "vra_fabric_network" "EXT_BE" {
  filter = "(name eq 'V1000' or name eq 'V2000') and cloudAccountIds.item eq '${vra_cloud_account_vsphere.vCenter_LAB.id}'" 
}
```

**Describe alternatives you've considered**
The only alternative in this case is to create a separate data source for each network, then add them in array when creating the network profile.

**Additional context**
Current implementation of data source for fabric_network expects the filter to get a maximum of one result.

**Comment by cars** [comment]
@hadrouj you can assign multiple networks while still only creating one data source using Terraform features.  An example is shown below:

In my variables.tf I have a variable ```subnet_names``` defined as a list(array) of the names of the subnets I want to add
```tf
variable "subnet_names" {
  type = list
}
```
In my tfvars file I have that list populated with two values
```tf
subnet_names = [
    "Public 1",
    "Public 2"
]
```
Then in the module you can use ```count``` in the resource: 
```tf
data "vra_fabric_network" "subnets" {
  count  = length(var.subnet_names)
  filter = "name eq '${var.subnet_names[count.index]}'"
}
```

Then in the actual network profile resource you can do 
```tf
resource "vra_network_profile" "example" {
  name      = "count_example"
  region_id = data.vra_region.this.id
  // Assign multiple values 
  fabric_network_ids = data.vra_fabric_network.subnets[*].id

}
```

The output of ```terraform plan```  shows that both fabric_networks are being looked up and then assigned... 

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be      
persisted to local or remote state storage.

data.vra_cloud_account_vsphere.this: Refreshing state...
data.vra_fabric_network.subnets[0]: Refreshing state...
data.vra_fabric_network.subnets[1]: Refreshing state...
data.vra_region.this: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vra_network_profile.example will be created
  + resource "vra_network_profile" "example" {
      + custom_properties  = (known after apply)
      + external_region_id = (known after apply)
      + fabric_network_ids = [
          + "85cc701b-5c12-4185-9e57-5b22a5c8a8f7",
          + "1b3bf4b7-cae0-418d-aced-17d43858c1bc",
        ]
      + id                 = (known after apply)
      + links              = (known after apply)
      + name               = "count_example"
      + organization_id    = (known after apply)
      + owner              = (known after apply)
      + region_id          = "65c8e221-878b-42b7-a5c3-171c93bc67a2"
      + updated_at         = (known after apply)

      + tags {
          + key   = (known after apply)
          + value = (known after apply)
        }
        }
        }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
HTH

**Comment by dmettem** [comment]
Thanks @cars for chiming in and suggesting a solution. I see this 

Is there any benefit having a dedicated data source with multiple results considering we have a way to achieve this already?

If not, this may be closed based on the approach suggested in previous comment.

**Comment by hadrouj** [comment]
Thanks @cars for the suggested solution. 
Indeed, I think this would do it. closing the ticket as resolved.
