### ISSUE TITLE
Fail to deploy a vra_machine resource on vSphere with error : Error: Provisioning operation failed. Expected vc:// scheme, found ubuntu

### ISSUE THREAD

**Issue by moffzilla** [vmware/terraform-provider-vra#242]
vRA 8.1. ( but also observed in vRA 8.2 pre-release ) 
Terraform v0.13.3
+ provider registry.terraform.io/vmware/vra v0.3.2

**Describe the bug**
Fail to deploy a vra_machine resource on vSphere 6.7 with error : **Error: Provisioning operation failed. Expected vc:// scheme, found ubuntu1804bis**

I followed the example for "vra_machine" and adapted for vSphere, the TF configuration files declares a profile resource, an image resource, block devices and the vra_machine.
All the resources are created but when the vra machine is tried, I observed that it gets created at vSphere but it fails to power on, and 
the Terraform error from above is displayed

The vRA Image mapping name are the same as the vSphere Template (ubuntu1804bis) 

**To Reproduce**
1.  Apply the Terraform configuration files attached targeting a vSphere 6.7

**Expected behavior**
Create all the resources and deploy a single VM in vSphere

**Logs**
I attach the full trace log "terraform_armagh.log"logs to help debug the issue
1. Attach vra-terraform.log and base TF configuration files

[vra_machine_resource-failed.tar.zip](https://github.com/vmware/terraform-provider-vra/files/5308060/vra_machine_resource-failed.tar.zip)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by dmettem** [comment]
@moffzilla - I suspect this issue may be because image_profile is created with image_mapping in which the name of the image is used instead of image id.

Can you try to create image_profile with image id in the image_mapping instead of name and try again? Thanks!

**Comment by moffzilla** [comment]
Thank you for your reply,  
I also noticed a problem with vRA itself, it was having issues referencing to the images directly at UI, after fixed that issue, then upgraded the vRA Provider to 0.3.3 and also removed the image_profile altogether and  call the image within the resource vra_machine using the image name

As of now the issue is gone so we could close this request as an issue in the vRA itself rather than in the provider

**Comment by dmettem** [comment]
@moffzilla - Thanks for providing the update. Closing the issue.
