### ISSUE TITLE
vra_machine resource custom_properties and extraConfig properties

### ISSUE THREAD

**Issue by ziurjam** [vmware/terraform-provider-vra#268]
vRA version
The vRA Cloud / 8.x version using.
Terraform version
The terraform version
terraform-provider-vra plugin version
The terraform-provider-vra plugin version

Hi I am trying to add a property "guestinfo.userdata" into config/extraConfig. Is it possible to leverage custom_properties to complete this task?
We are trying to use cloud-init-vmware-guestinfo as datasource for cloud-init to bootstrap a vm. I tried to setup the network with ovf cloud-init datasoruce, but it looks like ovf only inject user-data payload to boot-disk image. 
Thanks in advance

**Comment by dmettem** [comment]
@ziurjam - Please elaborate what you are trying to achieve and also the providers (if any other than vra) and resources you are using? Thanks!
