### ISSUE TITLE
Multiple projects creation using instance option

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#272]
vRA version
The vRA Cloud / 8.2 version using.
Terraform version
0.13.3
terraform-provider-vra plugin version
0.3.2

**Is your feature request related to a problem? Please describe.**
I need to create two projects using similar and some unique properties.  When I use instance = 2, terraform throws below error:

```
Error: Unsupported argument

  on main.tf line 24, in resource "vra_project" "dev":
  24:   instance                = 2

An argument named "instance" is not expected here.
```

**Describe the solution you'd like**
if an option is available like `instance = x`, then I can create multiple projects with single `resource "vra_project"`

**Describe alternatives you've considered**
I am using two .TF files to create multiple projects with most of the options are similar.

**Additional context**
na

**Comment by dmettem** [comment]
You can use `count` or `for_each` to do this.

**Comment by VickyWinner** [comment]
It works well with for_each.  So I can live with that for now.  are we going to have `instance` property/option in `resource "vra_project"`?
