### ISSUE TITLE
missing key in data network structure 

### ISSUE THREAD

**Issue by hobovirtual** [vmware/terraform-provider-vra#273]
**vRealize Automation version**
8.2

**Terraform version**
0.13.5

**terraform-provider-vra plugin version**
0.3.3

**Is your feature request related to a problem? Please describe.**
Cloud Template with a Cloud.vSphere.Machine and Cloud.NSX.Network

When running a deployment with terraform, when trying to get the IP Address of the Cloud.vSphere.Machine using the example in documentation 

```
output "addresses_by_name" {
  description = "Resource name and IP addresses of all machine type resources from a vRA deployment"
  value = {
    for props in sort(vra_deployment.this.resources.*.properties_json) :
    jsondecode(props).resourceName => jsondecode(props).address
    if jsondecode(props).componentType == "Cloud.Machine" || jsondecode(props).componentType == "Cloud.vSphere.Machine" || jsondecode(props).componentType == "Cloud.AWS.EC2.Instance" || jsondecode(props).componentType == "Cloud.GCP.Machine" || jsondecode(props).componentType == "Cloud.Azure.Machine"
  }
}
```

we get the following error
Error: Unsupported attribute

The issue is that the Cloud.NSX.Network property_json doesn't include the componentType key

**Describe the solution you'd like**
Add the componentType key in the data source for network

**Comment by dmettem** [comment]
@hobovirtual - Can you share the `vra_deployment` resource configuration and also the debug log?

**Comment by hobovirtual** [comment]
@dmettem please see the attached files
i've put the tfstate file you can see the properties_json for both resources
thanks!
[terraform.log](https://github.com/vmware/terraform-provider-vra/files/5447146/terraform.log)
[terraform_tfstate.txt](https://github.com/vmware/terraform-provider-vra/files/5447152/terraform_tfstate.txt)
