### ISSUE TITLE
data source for attaching existing zones to new project.

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#274]
vRA version
8.1
Terraform version
0.13.3
terraform-provider-vra plugin version
0.3.2

**Is your feature request related to a problem? Please describe.**
I have pre-created zones.  I am creating a new project and I am looking for some data source so it can allow to fetch the cloud zones and later I can attach/tag them to newly created project.

**Describe the solution you'd like**
`data source` not sure if it already exists but I couldn't find one.

**Describe alternatives you've considered**
I am passing cloud zones in variables and passing them to `vra_project` resource as shown in below example:

```hcl
data "vra_zone" "this" {
   name = var.cloud_zone
}
```

**Additional context**

**Comment by dmettem** [comment]
The data source `vra_zone` expects name to fetch the zone details. 

If you are looking to fetch the zones created for regions of a cloud account, it is not available in the provider.

You may refer here to the project example here on how to look up zone and assign to project: https://github.com/vmware/terraform-provider-vra/blob/master/examples/project/main.tf.

**Comment by VickyWinner** [comment]
@dmettem 
Thanks.  It would be a great benefit if there is a data source for fetching the cloud zones rather than passing them manually.

**Comment by VickyWinner** [comment]
> The data source `vra_zone` expects name to fetch the zone details.
> 
> If you are looking to fetch the zones created for regions of a cloud account, it is not available in the provider.
> 
> You may refer here to the project example here on how to look up zone and assign to project: https://github.com/vmware/terraform-provider-vra/blob/master/examples/project/main.tf.

your example [here](https://github.com/vmware/terraform-provider-vra/blob/1db1d7ec56a2ca4371dbaafefafdd4ac1c2a7295/examples/project/main.tf#L7),  I see you are passing values in variables. Looks like the look up is only done when you are passing zone name(s).  Can you we consider having a data source to fetch zones to retrieve all of them or based on a condition?
