### ISSUE TITLE
[Missing Feature] - Fetch & Add CloudTemplates to newly created project 

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#275]
vRA version
vRealize Orchestrator 8.2.0.16941495

Terraform version
Terraform v0.13.1

terraform-provider-vra plugin version
terraform.io/vmware/vra v0.3.3

**Is your feature request related to a problem? Please describe.**
I have pre-created cloud templates in vRA using UI.  I am creating a TF module to create project on use basis and tag pre-created cloud templates to newly created project.

**Describe the solution you'd like**
I am looking a way to tag existing cloudTemplates to newly created project.  I see currently there is an API endpoint `/catalog/api/admin/entitlements` using which we can do this but I am looking for a data source  in terraform to fetch existing cloud template and assign to a new project created using Terraform.

**Describe alternatives you've considered**
using an API endpoint `/catalog/api/admin/entitlements`

**Additional context**

**Comment by VickyWinner** [comment]
need this feature.

**Comment by Prativa20** [comment]
@VickyWinner Need some clarification. Are you looking for a data source for catalog item?

**Comment by VickyWinner** [comment]
@Prativa20 data source for [catalog item](https://registry.terraform.io/providers/vmware/vra/latest/docs/data-sources/vra_catalog_item) already exists, however, I cannot create entitlement using it.  right now I am creating entitlement using below method.  However, this way I get all the cloud templates from the project.  I am looking for creating entitlement from a catalog item by its name so that I can create entitlements based on its name, not based on the project in which the catalog exists.  did I make sense?

```hcl
data "vra_project" "project_template" {
  name = var.project_template
}

data "vra_catalog_source_blueprint" "this" {
  project_id = data.vra_project.project_template.id
}

data "vra_project" "this" {
  count      = var.project_count
  name       = vra_project.this[count.index].name
  depends_on = [vra_project.this]
}

resource "vra_catalog_source_entitlement" "this" {
  count             = var.project_count
  catalog_source_id = data.vra_catalog_source_blueprint.this.id
  project_id        = data.vra_project.this[count.index].id
}
```

**Comment by VickyWinner** [comment]
@Prativa20 Was that clarification helpful?  Is this being considered as an valid enhancement?

**Comment by VickyWinner** [comment]
@frodenas, Well, I moved to an alternate process outside Terraform.  couldn't wait this long as we need to create/manage projects using automation.

**Comment by frodenas** [comment]
The `catalog_item_entitlement` datasource and resource have been delivered as part of [v0.5.0](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.5.0).
