### ISSUE TITLE
implicit dependency doesn't work inside vra_project data source 

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#284]
**vRA version**
vRealize Automation 8.2.0.12946 (16980951)
**Terraform version**
Terraform v0.13.1
**terraform-provider-vra plugin version**
v0.3.3

**Describe the bug**
I am creating a new project followed by creating data source object so I can use the project resource further in my code.  When I run `terraform plan` below error.  I see that the implicit dependency is not being considered in the data source.  Here is sample code.

```hcl
resource "vra_project" "this" {
.
.
.
}

data "vra_project" "newproject" {
  for_each = vra_project.this
  name = vra_project.this[each.key].name
}
```

However, when I use `depends_on = [vra_project.this]` inside data source, it works.  does the implicit dependency doesn't work when using `name = vra_project.this[each.key].name` or `for_each = vra_project.this` ?

**To Reproduce**
1. Simply refer the above code and make changes where necessary
2. run `terraform plan`.  Don't use explicit `depends_on = [vra_project.this]`.
3. Error
```
Error: project xxxxxxxx not found

  on main.tf line 58, in data "vra_project" "newproject":
  58: data "vra_project" "newproject" {
```

**Expected behavior**
`terraform plan` shouldn't return any error which happened when I use depends_on exclusively.

**Screenshots**
n/a

**Logs**
**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by dmettem** [comment]
Hi @VickyWinner - When a resource/data source is referred in another resource/data source, terraform will / should create the implicit dependency and the providers doesn't have to handle this.

Can you please share the complete configuration for project resource and data source to confirm if I understood the issue correctly?

**Comment by VickyWinner** [comment]
Sorry for responding lately.  I was able to continue with the workaround so didn't get a chance to follow up.  Here is the configuration.

```hcl
resource vra_project this {
  name        = var.project_name
  description = var.project_description
}

  shared_resources        = var.share_resources
  administrators          = var.administrators
  members                 = var.members
  viewers                 = var.viewers
  operation_timeout       = var.operation_timeout //6000
  machine_naming_template = "$${resource.name}-$${####}"
}

data vra_project this {
  name       = vra_project.this.name  //this line should automatically create implicit dependancy per my understanding.
  depends_on = [vra_project.this] // I am forced to use this line to create dependancy.
}
```

Let  me know if you need log file.

**Comment by dondon3345678** [comment]
Hi, could you provide detail log file for debugging?

Thanks

**Comment by VickyWinner** [comment]
@dondon3345678 this still happens with TF version 0.13.3 I recently upgraded to 0.14.8 and I don't see this issue here. I tested with provider version 0.3.3/0.3.6 too.

Here is the log incase you would like to fix for old TF version.  else I can close it.
https://gist.github.com/VickyWinner/bd359007915c111961097ef8f4b41db7
