### ISSUE TITLE
Add Custom properties in resourceProject

### ISSUE THREAD

**Issue by mars4life** [vmware/terraform-provider-vra#291]
vRealize Automation 8.2.0.12959 (17018654)
terraform-provider-vra plugin version v0.3.3

Hello,

**Is your feature request related to a problem? Please describe.**
I use terraform to automatically create a new project on my vRA 8.2 On Prem platform .
I need to add a Custom Propertie for each project I created and I haven't find a way to do it with the provider.

**Describe the solution you'd like**
Is it possible to add the "Custom Properties" parameter in the resource named "Project" ?
like the machine_naming_template for example.

Thanks

**Comment by glingvmware** [comment]
Hi, is this feature in the Roadmap? If it is, would it possible to have a target date? Our customer has the same requirement. Thanks.

**Comment by wilsonandvmware** [comment]
Hi, i will work on this feature and update in this thread. it should be in our next monthly release.

**Comment by wilsonandvmware** [comment]
I have merged my enhancement https://github.com/vmware/terraform-provider-vra/pull/344 Please verify.

**Comment by glingvmware** [comment]
Hi, Thanks for the fix. I just tested it. Is it expected that we can only create/update custom properties but can not delete existing one(s) regardless those are created or not via terraform ?

**Comment by mars4life** [comment]
seems good to me, I've just test it.
Like said in the previous comment, delete existing custom_properties doesn't work

**Comment by wilsonandvmware** [comment]
Hi I was on training for the last week, I will take a look on the deletion flow this week

**Comment by wilsonandvmware** [comment]
I have talked to our IaaS API team and they confirmed there is a limitation coming from the update project api where it adds the new properties to the current existing properties, but not updating the custom properties directly. As a workaround, could you try to set your key-value pair entry to `key:null` in your custom property and retry terraform apply to delete existing custom_properties? @glingvmware  @mars4life
