### ISSUE TITLE
vra_fabric_network don't return nsxt network

### ISSUE THREAD

**Issue by supernini** [vmware/terraform-provider-vra#300]
**vRA version**
8.2 patch 1
**Terraform version**
0.14.5
**terraform-provider-vra plugin version**
0.3.3

**Describe the bug**
When we use the vra_fabric_network to add network to a network profile, we received this message :
vra_fabric_network must filter to a fabric network

**To Reproduce**
we need 
- 1 nsxt
- 1 vcenter

```
data "vra_fabric_network" "prod" {
  filter = "name eq 'toto'"
}
```

```
resource "vra_network_profile" "prod" {
  ...
  fabric_network_ids = [
    data.vra_fabric_network.prod.id
  ]
  ...
}
```

**Expected behavior**
Create the network profil and add the network

**Comment by vrabbi** [comment]
possibly related to #178

**Comment by supernini** [comment]
Hi vrabbi, not sure it's related to #178, coz I using 8.2patch1 and the search by nsxt network tags seem don't work too

**Comment by Prativa20** [comment]
@supernini I could reproduce this issue but to unblock yourself, you can also add the cloud account id in the filter. I will look into the code and get back to you.

`
data "vra_fabric_network" "subnet" {                                                                 
   filter = "name eq '<network-name>' and cloudAccountId eq '<cloud-account-id>'"
 } 
`
Thanks,
Prativa

**Comment by wilsonandvmware** [comment]
@supernini  it is returning `vra_fabric_network must filter to a fabric network` because the get fabric network api finds two networks from your nsxt and vsphere account with the same name. Can you check if both the nsxt and vsphere has `toto` ?

You can pass the issue by providing the cloudAccountId just like what Prativa suggested.

**Comment by supernini** [comment]
Sorry for my late reply.

But I update Cloud Assembly to 8.3 patch 1, and terraform to the last version

I try with Prativa20 suggest, the it's the same. In the cloud-account-id is set the nsxt.

**Comment by wilsonandvmware** [comment]
Hi @supernini  could you provide the full tf file when you added the cloud account id if possible? for me I tried the following code to get a network from nsxt account
`data "vra_fabric_network" "subnet" {
  filter = "name eq 'out-mcm246-xxxxxx' and cloudAccountId eq '7f0xxx-dbc0-xxx-asde-hfyyxxx'"
}`

**Comment by tenthirtyam** [comment]
+1 for @Prativa20 's recommendation to update the filter.

```
data "vra_cloud_account_nsxt" "this" {
  name = var.cloud_account_nsxt
}

data "vra_fabric_network" "this" {
  filter = "name eq '${var.subnet_name}' and cloudAccountId eq '${data.vra_cloud_account_nsxt.this.id}'"
}
```
