### ISSUE TITLE
Dynamic tag assignment for resources that support tags

### ISSUE THREAD

**Issue by stvkpln** [vmware/terraform-provider-vra#302]
vRA version: Any; relevant on SaaS and on premises releases
Terraform version: 0.14.5
terraform-provider-vra plugin version: 0.3.4

**Is your feature request related to a problem? Please describe.**
I need to be able to provide tags to resource blocks as map. For some of the resources that get created, particularly higher level constructs like cloud accounts, I'm typically using the same tags. I'd like to define and declare as few times as possible.

**Describe the solution you'd like**
Ideally, I'd like to be able to declare my list of tags in a key/value mapping of some kind, either as an input variable or via a local resource, and be able to pass that value map to the tags attribute of whatever resource block I care about, similar to how it works in this example: https://weidongzhou.wordpress.com/2018/12/13/how-to-do-tagging-efficiently-in-terraform/

**Describe alternatives you've considered**
I'm currently statically defining all of these tag blocks one by one and copy and pasting things around. It's very, very, very painful and not very flexible.

**Additional context**
Please feel free to reach out with questions!

**Comment by vrabbi** [comment]
this is already possible as of terraform 0.12 using dynamic blocks. bellow is an example of what it looks like for an AWS ASG but the same logic can be used as well for VRA as this is a common construct of Terraform 0.12+. for more info take a look at the following link: [https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each](url)
```terraform
locals {
  standard_tags = {
    Component   = "user-service"
    Environment = "production"
  }
}

resource "aws_autoscaling_group" "example" {
  tag {
    key                 = "Name"
    value               = "example-asg-name"
    propagate_at_launch = false
  }
  dynamic "tag" {
    for_each = local.standard_tags
    content {
      key                 = tag.key
      value               = tag.value
      propagate_at_launch = true
    }
  }
}
```

**Comment by stvkpln** [comment]
Today, I learned!! Thank you, @vrabbi... that got the job done. I'll close this out.
