### ISSUE TITLE
Deployments not updating correctly

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#303]
**vRA version**
The vRA Cloud / 8.x version where is issue is found. 8.0 and 8.2
**Terraform version**
The terraform version Terraform v0.12.24
**terraform-provider-vra plugin version**
The terraform-provider-vra plugin version 0.3.4

**Describe the bug**

If you create a deployment, then a resources is deleted outside of terraform the provider will not recreate the device.
EX:  If you create a deployment of 10 VMs and one VM needs to be deleted due to an issue with it.  VM gets deleted.  Run terraform apply and it does not recreate the device it just updates the state with the current resources in the deployment.

If a VM is deleted outside of a deployment in VRA and then you run update on the deployment the VM would be added.  

**To Reproduce**

1.  Create a deployment in VRA of multiple machines.
2. Delete a VM
3. Run terraform apply 

**Expected behavior**
This should update and add back the deleted VM as it does in VRA UI.

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)

**Desktop (please complete the following information):**

**Additional context**

**Comment by mdittbrenner215** [comment]
Here is image of initial VMs created to show 1 deployment with 10 count of VMs for 10 VMs
![Screen Shot 2021-02-03 at 2 40 25 PM](https://user-images.githubusercontent.com/56897611/106799925-d2bb8c00-662d-11eb-92fc-81a5f4521333.png)

**Comment by mdittbrenner215** [comment]
Screenshot with 10 VMs and IPs
![Screen Shot 2021-02-03 at 2 46 01 PM](https://user-images.githubusercontent.com/56897611/106800555-99375080-662e-11eb-8429-b994b62bfca5.png)

**Comment by mdittbrenner215** [comment]
After deleting 2 VMs in VRA I can update in VRA and it will re-add the two VMs.
![Screen Shot 2021-02-03 at 2 49 20 PM](https://user-images.githubusercontent.com/56897611/106800895-0cd95d80-662f-11eb-8210-9362641c6485.png)

**Comment by mdittbrenner215** [comment]
If i run terraform apply again it just make it with 8 VMs instead of adding back the 2 VMs
![Screen Shot 2021-02-03 at 2 50 43 PM](https://user-images.githubusercontent.com/56897611/106801024-37c3b180-662f-11eb-877f-a3e34c8880ff.png)

**Comment by mdittbrenner215** [comment]
Also when i update in VRA to add those two VMs back, and run terraform apply  it brings the two new VMs back into the state/outputs

**Comment by Prativa20** [comment]
Hi @mdittbrenner215 When managing deployment via terraform provider/APIs, if any changes are made via UI, the provider may not behave exactly like UI. An alternative in such cases would be to create the resources individually and not associate them with a deployment instead of using catalog item. That will enable to perform further actions on individual machines via provider itself.

**Comment by mdittbrenner215** [comment]
Unfortunately we are unable to do that as we are using network profiles for ip address management, which can not be used when creating machines via the IAAS api (unless that has changed in newer versions)

**Comment by Prativa20** [comment]
Hi @mdittbrenner215 The IP address management will be same in both cases. You can create a network profile via the TF provider or just have the profile(s) created via UI. You can create networks via provider and add to the profile(s).
Once all this is setup (via UI or provider), you can provision a machine and it will automatically assign IP address to the machine the way it is doing via UI.

Examples to create a network profile
https://github.com/vmware/terraform-provider-vra/tree/master/examples/network_profile

You can either create new networks or use fabric networks to add in the profile
And then go ahead and create machines.

Let me know if there are any more questions.
