### ISSUE TITLE
"vra_image" data source returns Images that don't belong to added Cloud Accounts

### ISSUE THREAD

**Issue by sam-perrin** [vmware/terraform-provider-vra#306]
**vRA version**
vRA Cloud
**Terraform version**
v0.14.5
**terraform-provider-vra plugin version**
v0.3.4

**Describe the bug**
Providing a simple name such as "ubuntu" or "photon" for the filter on data source "vra_image" returns images that do not belong to any added cloud accounts, causing the data source to fail with the error message `Error: vra_image must filter to a single image`.

**To Reproduce**
1. Add data source "vra_image"

```
provider "vra" {
  url           = var.vra_url
  refresh_token = var.vra_refresh_token
}

# Collecting Data Collector ID (used primarily for vRA Cloud)
data "vra_data_collector" "dc" {
  count = var.vc_datacollector != "" ? 1 : 0
  name  = var.vc_datacollector
}

# Collecting vSphere Region Data:
data "vra_region_enumeration_vsphere" "this" {
  username                = var.vc_username
  password                = var.vc_password
  hostname                = var.vc_hostname
  accept_self_signed_cert = true
  dcid                    = var.vc_datacollector != "" ? data.vra_data_collector.dc[0].id : ""
}

# Creating the vSphere Cloud Account and Associating the above NSX-V to it:
resource "vra_cloud_account_vsphere" "this" {
  name        = var.cloud_account_name
  description = var.cloud_account_description
  username    = var.vc_username
  password    = var.vc_password
  hostname    = var.vc_hostname
  dcid        = var.vc_datacollector != "" ? data.vra_data_collector.dc[0].id : "" # Required for vRA Cloud, Optional for vRA 8.0
  regions     = data.vra_region_enumeration_vsphere.this.regions
  accept_self_signed_cert = true
}

# 10 second delay for vSphere resources to collect:
resource "null_resource" "delay" {
  depends_on = [vra_cloud_account_vsphere.this]
  provisioner "local-exec" {
    command = "ping 127.0.0.1 -n 10 > NULL"
  }
  triggers = {
    "my_zone" = vra_cloud_account_vsphere.this.id
  }
}

data "vra_image" "this" {
  depends_on = [null_resource.delay]
  filter = "name eq 'ubuntu'"
}

```
2. Terraform apply 
3. Error `vra_image must filter to a single image`

**Expected behavior**
Data source "vra_image" should only return images from linked/added cloud accounts.

**Workaround/Alternate Solution**
Using a filter with cloudAccountId adds the image as expected from the added cloud account.
```
data "vra_image" "ubuntu" {
  depends_on = [null_resource.delay]
  filter     = format("%s%s%s", "name eq 'ubuntu' and cloudAccountId eq '", vra_cloud_account_vsphere.this.id, "'")
}
```

**Logs**
terraform.log attached. 
 - Line 3 shows API call with "ubuntu" name filter. 
 - Line 35 shows response with images from AWS

[terraform.log](https://github.com/vmware/terraform-provider-vra/files/5978562/terraform.log)

**Comment by sam-perrin** [comment]
Upon some further thought, this is likely just an API issue - rather than a Terraform provider issue.

**Comment by wilsonandvmware** [comment]
hi @sam-perrin  i see you have both vsphere and nsxt account added to your vRA, the get api finds two images from your nsxt and vsphere account with the same name and expect to have only one single images. The workaround you mentioned will unblock you by specifying cloud account id.

**Comment by Prativa20** [comment]
@sam-perrin Can we close this issue?

**Comment by tenthirtyam** [comment]
Definitely a filtering issue.

**Comment by sam-perrin** [comment]
@Prativa20 yes please close. Will do some more testing in the future. Seems to be a vRA Cloud issue though, as the images returned were not ones I had within any connected environment, so they must have been pulled from somewhere.
