### ISSUE TITLE
Unable to create on-demand network profile against a new NSX-T cloud account

### ISSUE THREAD

**Issue by sentania** [vmware/terraform-provider-vra#307]
**vRA version**
8.3
**Terraform version**
0.14.6 (observed on 0.13 also)
**terraform-provider-vra plugin version**
0.3.4

**Describe the bug**
When creating a network profile to create an on-demand network with NSX-T.  If the NSX-T manager is added as a cloud account in the same apply as the network profile creation, the profile creation fails to find the network domain created as part of a data filter.

A second apply correctly creates the network profile.

**To Reproduce**
https://github.com/sentania/vraPrivateCloudDemo/tree/devel
See networkprofile.tf and ondemandnetworkprofile module definition.

**Expected behavior**
The network profile should be created as specified using a newly added cloud account.

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)

**Desktop (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/2688043/108151324-0e2d7000-709c-11eb-8652-3ad38aabc854.png)

**Comment by dondon3345678** [comment]
Hi @sentania, I saw you have nsx-t provider specified in `vraPrivateCloudDemo/main.tf` and I'd like to know the purpose of it. To add NSX-T manager cloud account and network profile, it doesn't need that nsx-t provider. You can specify a `resource vra_cloud_account_nsxt` in the `networkProfiles.tf`.

**Comment by sentania** [comment]
A different issue I am facing is that when I want to create an on-demand network profile there doesn't appear to be a way to determine the pertinent information that the NP needs for NSX: 
* edgeClusterRouterStateLink 
* tier0LogicalRouterStateLink 

And the NSX-t provider being included was an effort by me trying look up information about them in NSX to pass to vRA, but the values expected by those appear to be private to vRA and not exposed via a public API as best I can tell.

https://github.com/sentania/vraPrivateCloudDemo/blob/devel/nsxOnDemandNetworkProfile/main.tf

https://github.com/sentania/vraPrivateCloudDemo/blob/devel/networkProfiles.tf
