### ISSUE TITLE
vra_catalog_source_entitlement - example

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#308]
I don't see an example for catalog source entitlement.  I am trying to tag an ABX action, content source etc to a new project and I don't find an example to refer to.  Documentation [here](https://registry.terraform.io/providers/vmware/vra/latest/docs/resources/vra_catalog_source_entitlement#source_type) doesn't detail out what is `source_type` and `type` accepted values etc.

**Comment by VickyWinner** [comment]
Below link explains how to share a content source to a project. I am trying to achieve the same using Terraform.

https://docs.vmware.com/en/vRealize-Automation/8.3/Using-and-Managing-Service-Broker/GUID-95F17E4A-9B26-401A-842D-1D4CDE03D196.html

**Comment by 06logan06** [comment]
> Below link explains how to share a content source to a project. I am trying to achieve the same using Terraform.
> 
> https://docs.vmware.com/en/vRealize-Automation/8.3/Using-and-Managing-Service-Broker/GUID-95F17E4A-9B26-401A-842D-1D4CDE03D196.html

I am also facing similar issue. Need to entitle content source to the project of type other than cloud templates. But no data source available to the content source details (extensibility actions, workflows,..)

**Comment by VickyWinner** [comment]
please consider this enhancement

**Comment by VickyWinner** [comment]
any update on this?
