### ISSUE TITLE
Bulk image profile creation not working

### ISSUE THREAD

**Issue by stvkpln** [vmware/terraform-provider-vra#309]
**vRA version**: 8.3.0.15014 (17551690) 
**Terraform version**: v0.14.7
**terraform-provider-vra plugin version**: v0.3.4

**Describe the bug**
When creating OS-specific image mappings for multiple regions, I end up with image mappings that somehow have duplicate resource id's... I'm ultimately seeing inconsistent results with what mappings are presented for each OS, but I never actually get more than 4-6, when there should be 8 under this circumstance. I truly hope I just have no clue what I'm doing with HCL at this point...

**To Reproduce**
The terraform code I'm using is:
```
locals {
    cent = "CentOS Linux 7 x86_64 HVM EBS ENA 1901_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-05713873c6794f575.4"
    deb  = "SupportedImages debian-stretch-hvm-x86_64-gp2-2020-0f258a51-0979-4be2-a6a9-ec8fe108514a-ami-0ec58a45652c1f042.4"
    cname = "CentOS 7"
    dname = "Debian 9"
    desc     = "Automated image mapping provisioning"
}

# Getting all of the relevant regions from the id's provided
data "vra_region" "cent_regions" {
  for_each = toset(module.zones_aws-kpsc.region_ids)
  filter = "id eq '${each.key}'"
}

# CentOS 7
data "vra_image" "cent" {
  for_each = data.vra_region.cent_regions
  filter   = "name eq '${local.cent}' and externalRegionId eq '${each.value.name}'"
}

resource "vra_image_profile" "cent" {
  for_each  = toset(module.zones_aws-kpsc.region_ids)
  name      = local.cname
  description = local.desc
  region_id = each.key

  image_mapping {
    name = local.cname
    image_id = data.vra_image.cent[each.key].id
  }
}

output "cent" {
  value = values(vra_image_profile.cent)[*].id
}

# Debian 9
data "vra_region" "deb_regions" {
  for_each = toset(module.zones_aws-kpsc.region_ids)
  filter = "id eq '${each.key}'"
}

data "vra_image" "deb" {
  for_each = data.vra_region.deb_regions
  filter   = "name eq '${local.deb}' and externalRegionId eq '${each.value.name}'"
}

resource "vra_image_profile" "deb" {
  for_each  = toset(module.zones_aws-kpsc.region_ids)
  name      = local.dname
  description = local.desc
  region_id = each.key

  image_mapping {
    name = local.dname
    image_id = data.vra_image.deb[each.key].id
  }
}

output "deb_profiles" {
  value = values(vra_image_profile.deb)[*].id
}
```

The module referenced above has an output that is:
```
output "region_ids" {
  description = "The resource id's for the enumerated regions"
  value = values(data.vra_region.regions)[*].id
}
```

In this instance, the regions I'm working with are in AWS; us-east-1, us-east-2, us-west-1, and us-west-2

The output I get is:
```
Outputs:
cent = [
  "60f7c9f2-c345-4591-a91e-f0471f58897e-23421605-947d-4256-84fa-9ab6ec5d3d52",
  "60f7c9f2-c345-4591-a91e-f0471f58897e-539c68cc-fe83-46bb-a194-405fe2f6dc58",
  "60f7c9f2-c345-4591-a91e-f0471f58897e-c4c3fb95-f583-482b-8d38-906536f6302e",
  "60f7c9f2-c345-4591-a91e-f0471f58897e-d0d30265-c31c-492c-8707-723bef367e3d",
]
deb_profiles = [
  "60f7c9f2-c345-4591-a91e-f0471f58897e-23421605-947d-4256-84fa-9ab6ec5d3d52",
  "60f7c9f2-c345-4591-a91e-f0471f58897e-539c68cc-fe83-46bb-a194-405fe2f6dc58",
  "60f7c9f2-c345-4591-a91e-f0471f58897e-c4c3fb95-f583-482b-8d38-906536f6302e",
  "60f7c9f2-c345-4591-a91e-f0471f58897e-d0d30265-c31c-492c-8707-723bef367e3d",
]
```

**Expected behavior**
I'd expect that those id's would not be identical matches and the vRA API would show me 8 image mappings

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)
[terraform.log](https://github.com/vmware/terraform-provider-vra/files/6046338/terraform.log)

**Desktop (please complete the following information):**
MacOS 11.2.1

**Additional context**

**Comment by wilsonandvmware** [comment]
Hey @stvkpln I'm trying to understand the issue here, are you trying to create two vra-image-profiles (cent and deb_profiles), and each has for different regions but with the same image name ? and the expected outputs are for the images ids within the image profile you just created?

**Comment by stvkpln** [comment]
> Hey @stvkpln I'm trying to understand the issue here, are you trying to create two vra-image-profiles (cent and deb_profiles), and each has four different regions but with the same image name ? and the expected outputs are for the images ids within the image profile you just created?

@wilsonandvmware maybe that code snippet didn't frame it up properly, but basically:
1. I'm creating two image profiles, one for Debian and one for CentOS
2. The AMI's I'm using have the same name across each region, so I'm using a for_each loop to query each AWS region for the relevant AMI
3. I'm then using a for_each loop of the data resource of each region to create the profile across AWS regions, using the id of the region to query for the AMI ID from the AMI data resource object.

What I end up with is inconsistent results where some of these profiles end up with some of the regions populated, but if I comment out and do a plan/apply, then uncomment out, I get different results on the next plan/apply... I never ultimately see 4 regions populated in either image profile.

Maybe I'm doing something wonky here, but I couldn't figure out a better way to be able to create these in bulk when I have a consistent naming mechanism for the image across regions. It'd be very impractical to create 8x data resources and 8x image_profile resources when looping should be an effective way of doing this.

**Comment by wilsonandvmware** [comment]
Hi @stvkpln  sorry for the late  reply, I got help from our API team to understand the use case after I reproduced the issue you described here. For their reply `The image/flavor profiles are region-scoped. By design, you can have at most 1 image/flavor profile per-region.` If there are same region_id, it will ends up with same id and overwrite the image profile after creating it. Could you please provide the `region_id` in your template ? I guess the 4 IDs you got from Debians and CentOS are for the 4 regions in your aws account.

**Comment by stvkpln** [comment]
@wilsonandvmware: thanks for the explanation; I just confirmed that that's what I'm seeing going on! Now that I understand the behavior, I can work around and figure out a different way to tackle this problem... If I can get on a soapbox for a second, though...

My principle concern as this wraps up is that the API and UI do not behave in the same ways and the way a person thinks about these things has to shift drastically depending on if they are operating through the UI or API. By that, I mean the following:

- In the API, your point of reference is on the region and building a list of images that are mapped against it. This makes great sense because when trying to do things in bulk, aligning against the region makes querying easier. I'm with you guys there!
- In the UI, however.... everything is aligned around that image mapping name and abstracting away that backend and really presenting it as the mapping is the top level resource that's managed.

I get that this isn't something that can be solved for in the provider, because it's beholden to what the API makes available, but somebody should have a serious conversation as capabilities are developed about these sorts of interactions because it's existentially frustrating trying to make things work based on how you think the product models things, only to discover consumption programmatically leads you down a dark rabbit hole that makes you have to think about things in a totally different way to get anywhere near a workable solution.  I'm glad I went through the exercise, because I get a lot more insight into the product... but most folks don't have time to figure out this sort of incoherence and will just give up.

If ever a v2 version of this API comes to light, I'd humbly request that this sort of disconnect between the UI and API gets resolved because things like this do not make it easy for anybody to adopt a programmatic approach to managing vRA.

I'll leave the PR open for the moment in case somebody wants to reply; otherwise, feel free to call this one closed. I'll point some of the PMs I know to this piece of feedback, as well, so they can take note. :)

**Comment by wilsonandvmware** [comment]
@stvkpln  thank you for the info.
