### ISSUE TITLE
vRA Project permissions - TF adds AD group as users

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#311]
**vRA version**
vRealize Automation 8.3.0.15014 (17551690)

**Terraform version**
Terraform v0.13.3

**terraform-provider-vra plugin version**
v0.3.4

**Describe the bug**
I am creating a new project and adding AD/vIDM group inside the `resource vra_project`.  However TF seems to be not sending it as a group when making an API call as a result, I see this group as a user.

**To Reproduce**
1. Terraform config file (for updates, config file before applying the change and the change made)
```hcl
resource vra_project this {
  name        = var.project_name

  administrators          = "xxx-xxx-grp" //Add AD/vIDM group instead of an account.
}
```
2. Terraform command
     `Terraform Apply`
3. Error
     `No errors`

**Expected behavior**
TF should add the AD/vIDM group as group and not as a user.

**Screenshots**
![project](https://user-images.githubusercontent.com/33285331/110547263-b2379380-80fd-11eb-8abc-f6f5f5d551dd.JPG)

**Logs**
Attach logs to help debug the issue
will send if required.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by VickyWinner** [comment]
I am reading that when a new project is created using an [API](https://docs.vmware.com/en/vRealize-Automation/8.2/extensibility-migration/GUID-B2BD562A-1AE0-4A1F-A6AA-79485436DEC4.html), the payload has vIDM/AD type.  Not sure how the provider is making this call.

**Comment by wilsonandvmware** [comment]
This is due to the iaas api does not support adding group along with projects yet.

**Comment by VickyWinner** [comment]
So, what is the workaround to add groups to `Administrator`, `Member` or `Viewer` access in Terraform?

**Comment by wilsonandvmware** [comment]
Just checked with the iaas api team, so we have support for adding users as groups using the iaas api, but not in the provider yet.

@dmettem Should we open a PR to add support for User model which should have `type: group` in addition to email ?

**Comment by dmettem** [comment]
Yes @wilsonandvmware. I've made the changes, currently waiting for testing.

**Comment by GaryFlynn** [comment]
I have just hit this exact issue with my own customer. Would be great to see a fix and release for this, as we must use TF to create the project, as opposed to the API which does support adding groups.

**Comment by VickyWinner** [comment]
@dmettem, Any estimate on when this will be released?

**Comment by dondon3345678** [comment]
Issue has been fixed. Please refer to the new fields to specify the type of users.
