### ISSUE TITLE
Day-2 action on a deployment

### ISSUE THREAD

**Issue by mars4life** [vmware/terraform-provider-vra#313]
vRealize Automation version 8.3.0.15014 (17551690)
Terraform version 0.14.5
The terraform-provider-vra plugin version 0.3.4

**Is your feature request related to a problem? Please describe.**
I want to manage my platform via terraform only.
For that, I would like to be able to perform Day-2 actions like adding an extra disk.

**Describe the solution you'd like**
Add the possibility to perform Day-2 actions related to resources via the terraform provider.

**Describe alternatives you've considered**
Taking the example of adding a disk, my need is to be able to add a standard disk to my deployment, as it is possible with the GUI.
I saw that it is possible to add a FirstClassDisk and then attach it to a deployment but only via the API.

Thanks

**Comment by frodenas** [comment]
This seems a duplicate of https://github.com/vmware/terraform-provider-vra/issues/290
