### ISSUE TITLE
Regression: Deployment 'owner' is no longer truly optional in 0.3.4

### ISSUE THREAD

**Issue by youeyoue** [vmware/terraform-provider-vra#317]
**vRA version**
8.3
**Terraform version**
0.14.4
**terraform-provider-vra plugin version**
0.3.4

**Describe the bug**
The first run creating a new deployment without setting 'owner' works fine.  However, subsequent runs after 'owner' discovery (known after apply) sees a change in state and tries to update the 'owner' to null (as it is absent from the config).

This issue only happens in vra provider version 0.3.4.  When reverting to 0.3.3, there is no issue and subsequent runs work as expected.

I believe this regression may be related to pull request #297.

**To Reproduce**
1. New deployment resource omitting 'owner' field in terraform config
2. Run `terraform apply`
3. After successful apply, run `terraform apply` again (or `terraform plan`)
4. Terraform sees an 'update in-place' is required to set 'owner' to null

**Expected behavior**
There shouldn't be any changes required during the second terraform operation and the proper terraform response should be:

`No changes. Infrastructure is up-to-date.`

**Screenshots**
N/A

**Logs**
N/A

**Desktop (please complete the following information):**
 - OS: OSX

**Additional context**

**Comment by dmettem** [comment]
Thanks @youeyoue for reporting.

Yes. The PR you mentioned has caused the failure. Working on the fix.
