### ISSUE TITLE
All password used to connect Cloud Accounts remain in terraform state as a text string.

### ISSUE THREAD

**Issue by jmandl** [vmware/terraform-provider-vra#322]
**vRA version**
The vRA Cloud / 8.4 version where is issue is found.
**Terraform version**
The terraform version v0.14.7
**terraform-provider-vra plugin version**
The terraform-provider-vra plugin version registry.terraform.io/vmware/vra v0.3.5

**Describe the bug**
I am using terraform to create all configs inside vRA, after I plan / apply all credentials necessary to create cloud zones (vRA <> vCenter) is saved in text inside terraform.tfstate.

**To Reproduce**

Code Example: 
```
data "vra_region_enumeration_vsphere" "thisloc" {
  username                = var.username
  password                = var.password
  hostname                = var.hostname_loc
  accept_self_signed_cert = true
}


resource "vra_cloud_account_vsphere" "datacenter-loc" {
  name        = "Datacenter"
  description = "Datacenter. Created by terraform."
  username    = var.username
  password    = var.password
  hostname    = var.hostname_loc
  regions     = data.vra_region_enumeration_vsphere.thisloc.regions

  tags {
    key   = "cloud"
    value = "datacenter-loc"
  }
}
```

After run plan / apply all password are exposed inside terraform state.

**Expected behavior**
As other providers is expected that this password was hashed or encrypted inside vRA.

**Screenshots**
There is no screenshot.

**Logs**
I cannot provide logs since is our production environment.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
![2021-04-26 14_43_46-](https://user-images.githubusercontent.com/15808652/116127256-0098f580-a69e-11eb-9839-67ff77a72193.png)

**Comment by markpeek** [comment]
@jmandl yes, this is the way terraform stores state data including sensitive fields such as passwords. The terraform docs discuss it [here](https://learn.hashicorp.com/tutorials/terraform/sensitive-variables#sensitive-values-in-state). And the vRA provider does mark the password fields as sensitive such as [here](https://github.com/vmware/terraform-provider-vra/blob/master/vra/resource_cloud_account_vsphere.go#L35).

**Comment by cars** [comment]
@jmandl  - if for some reason you can't use a remote backend (TF cloud, S3, http) and have to keep state files locally you can look at something like: [Terrahelp](https://github.com/opencredo/terrahelp) to encrypt the sensitive portions of your state file.  We were using this for encrypting the state file locally until we could move them to a remote backend.

**Comment by Prativa20** [comment]
@jmandl Can we close this issue?

**Comment by tenthirtyam** [comment]
@Prativa20 I agree, this should be clear to close.

Ryan

**Comment by jmandl** [comment]
Thanks for your help Partiva Bawri.



|João Paulo de Carvalho ***@***.***|+55 11 9 9121 4634|
