### ISSUE TITLE
Importing vRA Storage Profile doesn't import disk target properties and region ID

### ISSUE THREAD

**Issue by brude-softserve** [vmware/terraform-provider-vra#324]
**vRA version**
v8
**Terraform version**
v0.14.9
**terraform-provider-vra plugin version**
v0.3.5

**Describe the bug**
When running the `terraform import` command on a Storage Profile, the imported resources has `null` value for the `disk_target_properties` and `region_id` fields.

**To Reproduce**
1. Take the [example Terraform config](https://github.com/vmware/terraform-provider-vra/tree/master/examples/infrastructure_setup/vmc)
2. Run command `terraform import vra_storage_profile.this <existing_profile_id>`
3. Check the terraform state.

**Expected behavior**
The imported storage profile resource has the `disk_target_properties` field that contains all the properties and `region_id` with the actual region ID, so the storage profile can be deployed after the importing.

**Comment by Prativa20** [comment]
@brude-softserve The region id is only required while creating a storage profile. In the state file, it is translated to external_region_id. 
disk_target_properties is not returned by the API. This needs a fix in the product.

**Comment by brude-softserve** [comment]
> @brude-softserve The region id is only required while creating a storage profile. In the state file, it is translated to external_region_id.
> disk_target_properties is not returned by the API. This needs a fix in the product.

@Prativa20, When I do `terraform import vra_zone.this <existing_zone_id>`, both `region_id` and `external_region_id` are null in the state file.

**Comment by Prativa20** [comment]
Closing this as it is working as expected. @brude-softserve Please reopen or reach out if there are any questions.
