### ISSUE TITLE
Importing a network profile doesn't import IDs of the networks added to it

### ISSUE THREAD

**Issue by brude-softserve** [vmware/terraform-provider-vra#325]
**vRA version**
v8
**Terraform version**
v0.14.9
**terraform-provider-vra plugin version**
v0.3.5

**Describe the bug**
When running the `terraform import` command on a vRA network profile resource, the imported profile has `null` value in the `fabric_network_ids` field. So if create the network profile after importing it will not contain any networks.

**To Reproduce**
1. Take the [example Terraform config](https://github.com/vmware/terraform-provider-vra/tree/master/examples/infrastructure_setup/vmc)
2. Run command `terraform import vra_network_profile.this <existing_profile_id>`
3. Check the terraform state.

**Expected behavior**
The imported network profile resource has the list of its network IDs in the `fabric_network_ids` field.

**Comment by wilsonandvmware** [comment]
hi @brude-softserve  thanks for pointing out the issue, I think we need to update our model in provider to pick the fabirc-network id returned by the API, for the workaround, you should still see the fabric-network links under 
```
            "links": [
              {
                "href": "",
                "hrefs": [
                  "/iaas/api/fabric-networks/{id} ",
                  "/iaas/api/fabric-networks/(id}"
                ],
                "rel": "fabric-networks"
              }, 
```
it should have the network id in it.

**Comment by wilsonandvmware** [comment]
Fix is merged in https://github.com/vmware/terraform-provider-vra/pull/338
