### ISSUE TITLE
vRA resources cannot be created in a multi-account environment

### ISSUE THREAD

**Issue by brude-softserve** [vmware/terraform-provider-vra#327]
**vRA version**
v8
**Terraform version**
v0.14.9
**terraform-provider-vra plugin version**
v0.3.5

**Describe the bug**
In a multi-account environment Terraform cannot get correct region when creating resources hence cannot create them.
VMC regions from different accounts have the same `name` ('SDDC-Datacenter') and `externalRegionId` ('Datacenter:datacenter-3'). So the [suggested solution](https://github.com/vmware/terraform-provider-vra/blob/master/examples/infrastructure_setup/vmc/main.tf#L52-L53) doesn't work because the `vra_region` data source returns multiple records.

**To Reproduce**
1. Add multiple VMC accounts with the same region names to vRA.
2. Test the [example code](https://github.com/vmware/terraform-provider-vra/tree/master/examples/infrastructure_setup/vmc).

**Expected behavior**
The `vra_region` data source should support filtering by Cloud Account ID, e.g.:`cloudAccountId eq '${vra_cloud_account_vmc.this.id}`

**Comment by wilsonandvmware** [comment]
Could you provide the vRA build number / version please? is it 8.1 or 8.2? I think the region should support filter by cloud account id, but for VMC you need to use the associated vsphere cloud account id from that specific region, not just the id of the account.

**Comment by brude-softserve** [comment]
> Could you provide the vRA build number / version please? is it 8.1 or 8.2? I think the region should support filter by cloud account id, but for VMC you need to use the associated vsphere cloud account id from that specific region, not just the id of the VMC account.

Yes, you're right and it makes using the provider impossible because Terraform doesn't know the associated vsphere cloud account id. How can I get it in the my module? And how should I rewrite the filter query to make it work then?
Possible solution to this might be adding additional field (let say `vshpere_account_id`) to the `vra_cloud_account_vmc` resource and data source. In such case we'll be able to filter by this field.

As for the vRA version - it's 8.3.

**Comment by Prativa20** [comment]
@brude-softserve Can we close this issue?

**Comment by brude-softserve** [comment]
@Prativa20 @wilsonandvmware 
I didn't have a chance to test it with the latest Terraform and vra provider because our VMWare environment got broken and the support cannot fix it. But looking at one of the previous deployments, the `vra_cloud_account_vmc` contain only region name:
```json
            "regions": [
              "Datacenter:datacenter-3"
            ],
```
Did you test it on your side?

**Comment by wilsonandvmware** [comment]
Hi @brude-softserve,  with a 8.3 build and the latest terraform provider code, I was able to filter the region by `name`, `externalRegionId` and I use the `region_ ids `from the vmc account for `cloudAccountId`

```
           "region_ids": [
              "9b3b1cac-0af8-46e7-be5f-2dbdd3c5d337"
            ],
            "regions": [
              "Datacenter:datacenter-3"
            ],

```
main.tf
```
data "vra_region" "this" {
  filter = "externalRegionId eq 'Datacenter:datacenter-3' and cloudAccountId ne '9b3b1cac-0af8-46e7-be5f-2dbdd3c5d337'"
  name = "SDDC-Datacenter" 
}
```
Could you try the above approach and see if it works as a workaround, I agree we need to show the associated vsphere id and currently I don't see it in the vmc account tfstate, I think you can open a enhancement request for that.

**Comment by brude-softserve** [comment]
Hi @wilsonandvmware , thanks for reply!
Did you test this approach in the case when you have multiple VMC accounts that have `externalRegionId == 'Datacenter:datacenter-3'`?
I think we just got back to the initial problem that I described in the issue. Most of our VMC accounts have `externalRegionId == 'Datacenter:datacenter-3'`. Filtering with your example (`and cloudAccountId ne '9b3b1cac-0af8-46e7-be5f-2dbdd3c5d337'`) will return all of them (both vSphere and VMC) except only this one ('9b3b1cac-0af8-46e7-be5f-2dbdd3c5d337'), won't it?

**Comment by wilsonandvmware** [comment]
Hi @brude-softserve sorry I made a typo, it should be `eq` not `ne`. Let me include to full script, usually we don't have a second account with same region name, but we found one today so I can test.

In my main.tf I have two vmc account resources with same externalRegionId =  "Datacenter:datacenter-3" and the region name is also same("SDDC-Datacenter"). and I applied the following filter on externalRegionId and VMC cloud Account IDs

```
data "vra_region" "first" {
  filter = "externalRegionId eq 'Datacenter:datacenter-3' and cloudAccountId eq '4c6b9ebf-1a06-453e-b60d-4babbb439686'"
  name = "SDDC-Datacenter" 

}

data "vra_region" "second" {
  filter = "externalRegionId eq 'Datacenter:datacenter-3' and cloudAccountId eq '790404c8-cd7f-4e19-90d3-92a806c96786'"
  name = "SDDC-Datacenter" 
}

output region_first {
  value = data.vra_region.first.*
}

output region_second {
  value = data.vra_region.second.*
}
```

Here is the output I see, note the id is different, which we used to identify regions.

```
Outputs:

region_first = [
  {
    "cloud_account_id" = "4c6b9ebf-1a06-453e-b60d-4babbb439686"
    "created_at" = ""
    "external_region_id" = "Datacenter:datacenter-3"
    "filter" = "externalRegionId eq 'Datacenter:datacenter-3' and cloudAccountId eq '4c6b9ebf-1a06-453e-b60d-4babbb439686'"
    "id" = "ab3a3806-aaad-4497-951a-b5830118e5ab"
    "name" = "SDDC-Datacenter"
    "owner" = ""
  },
]
region_second = [
  {
    "cloud_account_id" = "790404c8-cd7f-4e19-90d3-92a806c96786"
    "created_at" = ""
    "external_region_id" = "Datacenter:datacenter-3"
    "filter" = "externalRegionId eq 'Datacenter:datacenter-3' and cloudAccountId eq '790404c8-cd7f-4e19-90d3-92a806c96786'"
    "id" = "86c2b4e5-a55b-4a73-93ff-b7f753dfd520"
    "name" = "SDDC-Datacenter"
    "owner" = ""
  },
]

```

Do you still see the initial problem here? Please let me know if you have any questions.

I used an 8.3 build and the latest terraform provider code.
