### ISSUE TITLE
For `vra_zone` resources, the `external_region_id` value is never know and every apply tries to change it

### ISSUE THREAD

**Issue by rnelson0** [vmware/terraform-provider-vra#329]
**vRA version**
8.3
**Terraform version**
0.15.1
**terraform-provider-vra plugin version**
0.3.5

**Describe the bug**
The `external_region_id` attribute of a `vra_zone` resource is calculated on apply, but is not known to terraform even after an apply, resulting in `terraform plan` showing 1 change per zone on every run

**To Reproduce**
1. Terraform config file (for updates, config file before applying the change and the change made)
```
resource "vra_zone" "bedford_zone" {
  name = "Bedford vCenter / Bedford"
  description = ""
  region_id = data.vra_region.bedford_region.id
}
```
2. Terraform command
terraform apply
3. Error
No error results, but incorrect behavior

**Expected behavior**
On the first run, I would expect `external_region_id` to be set and then saved in `terraform.tfstate`. On subsequent runs - absent any other changes - I would expect `external_region_id` to match and no change be required for the zone.

**Screenshots**
```
> terraform apply
...
vra_zone.bedford_zone: Refreshing state... [id=b7d98a66-7020-4d47-a46f-ddfe88caea52]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vra_zone.bedford_zone will be updated in-place
  ~ resource "vra_zone" "bedford_zone" {
      + external_region_id = (known after apply)
        id                 = "b7d98a66-7020-4d47-a46f-ddfe88caea52"
        name               = "Bedford vCenter / Bedford"
        # (7 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vra_zone.bedford_zone: Modifying... [id=b7d98a66-7020-4d47-a46f-ddfe88caea52]
vra_zone.bedford_zone: Modifications complete after 0s [id=b7d98a66-7020-4d47-a46f-ddfe88caea52]

> terraform plan
...
vra_zone.bedford_zone: Refreshing state... [id=b7d98a66-7020-4d47-a46f-ddfe88caea52]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vra_zone.bedford_zone will be updated in-place
  ~ resource "vra_zone" "bedford_zone" {
      + external_region_id = (known after apply)
        id                 = "b7d98a66-7020-4d47-a46f-ddfe88caea52"
        name               = "Bedford vCenter / Bedford"
        # (7 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
> 
```

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log 
[terraform.log](https://github.com/vmware/terraform-provider-vra/files/6400873/terraform.log)

2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)

**Desktop (please complete the following information):**
 - OS: Windows 10, pwsh 7

**Additional context**
I'm not sure what `external_region_id` is WRT to a project anyway. Once you create a zone you tie it to a region and that should be it.

I also tried adding an `ignore_changes` block like so without any difference:
```
resource "vra_zone" "bedford_zone" {
  name = "Bedford vCenter / Bedford"
  description = ""
  region_id = data.vra_region.bedford_region.id

  lifecycle {
    ignore_changes  = [
      external_region_id,
    ]
  }
}
```

**Comment by Prativa20** [comment]
The fix to set external_region_id is merged https://github.com/vmware/terraform-provider-vra/pull/330

**Comment by rnelson0** [comment]
I confirmed this fixes our issue. Thank you for the rapid turnaround!
