### ISSUE TITLE
Terraform plan or apply shows changes even if there were none

### ISSUE THREAD

**Issue by brude-softserve** [vmware/terraform-provider-vra#331]
**vRA version**
v8
**Terraform version**
v0.14.9
**terraform-provider-vra plugin version**
v0.3.5

**Describe the bug**
The `terraform plan` command always shows some changes and wants to update the resources even if there were none changes to the Terraform code.

**To Reproduce**
1. Take the [example code](https://github.com/vmware/terraform-provider-vra/tree/master/examples/infrastructure_setup/vmc).
2. Deploy the infrastructure: `terraform apply`.
3. Run `terraform plan` afterwards. The output will be like this:
```
...
# vra_flavor_profile.this will be updated in-place
  ~ resource "vra_flavor_profile" "this" {
      + external_region_id = (known after apply)
        id                 = "426f4a9a-6e4f-42e4-b9f1-67f1669f3351-13129130-9562-462d-aa3d-a420863a271c"
        name               = "VMC Flavor Profile"
        # (6 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
  # vra_network_profile.this will be updated in-place
  ~ resource "vra_network_profile" "this" {
      ~ fabric_network_ids           = [
          - "2115e037-aaf3-410e-bcaf-8c0d22620393",
        ] -> (known after apply)
        id                           = "4b8f3f98-ac07-4a1c-acc3-4df8efd937cb"
        name                         = "VMC Network Profile"
        # (11 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
  # vra_storage_profile.this will be updated in-place
  ~ resource "vra_storage_profile" "this" {
      ~ disk_target_properties = {
          - "datastoreId" = "8997efb8-b86c-4f5a-acd9-5a6cf55cfe18"
        } -> (known after apply)
        id                     = "def31f0e-2ac3-45c6-88c0-387b852243cd"
        name                   = "VMC Storage Profile"
        # (11 unchanged attributes hidden)
    }
  # vra_zone.this will be updated in-place
  ~ resource "vra_zone" "this" {
      + external_region_id = (known after apply)
        id                 = "f9fef26a-fea1-456a-b124-04af9c2903e1"
        name               = "VMC Zone"
        # (9 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
Plan: 0 to add, 4 to change, 0 to destroy.
```

**Expected behavior**
If there were no changes to the Terraform code, the change set should be empty when running `terraform plan` or `terraform apply` over an existing deployment.

**Comment by VickyWinner** [comment]
I had this issue too.

**Comment by VickyWinner** [comment]
> **vRA version**
> v8
> **Terraform version**
> v0.14.9
> **terraform-provider-vra plugin version**
> v0.3.5
> 
> **Describe the bug**
> The `terraform plan` command always shows some changes and wants to update the resources even if there were none changes to the Terraform code.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Take the [example code](https://github.com/vmware/terraform-provider-vra/tree/master/examples/infrastructure_setup/vmc).
> 2. Deploy the infrastructure: `terraform apply`.
> 3. Run `terraform plan` afterwards. The output will be like this:
> 
> ```
> ...
> # vra_flavor_profile.this will be updated in-place
>   ~ resource "vra_flavor_profile" "this" {
>       + external_region_id = (known after apply)
>         id                 = "426f4a9a-6e4f-42e4-b9f1-67f1669f3351-13129130-9562-462d-aa3d-a420863a271c"
>         name               = "VMC Flavor Profile"
>         # (6 unchanged attributes hidden)
>         # (1 unchanged block hidden)
>     }
>   # vra_network_profile.this will be updated in-place
>   ~ resource "vra_network_profile" "this" {
>       ~ fabric_network_ids           = [
>           - "2115e037-aaf3-410e-bcaf-8c0d22620393",
>         ] -> (known after apply)
>         id                           = "4b8f3f98-ac07-4a1c-acc3-4df8efd937cb"
>         name                         = "VMC Network Profile"
>         # (11 unchanged attributes hidden)
>         # (1 unchanged block hidden)
>     }
>   # vra_storage_profile.this will be updated in-place
>   ~ resource "vra_storage_profile" "this" {
>       ~ disk_target_properties = {
>           - "datastoreId" = "8997efb8-b86c-4f5a-acd9-5a6cf55cfe18"
>         } -> (known after apply)
>         id                     = "def31f0e-2ac3-45c6-88c0-387b852243cd"
>         name                   = "VMC Storage Profile"
>         # (11 unchanged attributes hidden)
>     }
>   # vra_zone.this will be updated in-place
>   ~ resource "vra_zone" "this" {
>       + external_region_id = (known after apply)
>         id                 = "f9fef26a-fea1-456a-b124-04af9c2903e1"
>         name               = "VMC Zone"
>         # (9 unchanged attributes hidden)
>         # (1 unchanged block hidden)
>     }
> Plan: 0 to add, 4 to change, 0 to destroy.
> ```
> 
> **Expected behavior**
> If there were no changes to the Terraform code, the change set should be empty when running `terraform plan` or `terraform apply` over an existing deployment.

Are you getting the same issue on 8.4?  Did you get a chance to test there?

**Comment by dondon3345678** [comment]
Issue is fixed in https://github.com/vmware/terraform-provider-vra/pull/341
