### ISSUE TITLE
Multiple storage profiles for a single region show up as multiple regions

### ISSUE THREAD

**Issue by brude-softserve** [vmware/terraform-provider-vra#332]
**vRA version**
v8
**Terraform version**
v0.14.9
**terraform-provider-vra plugin version**
v0.3.5

**Describe the bug**
When adding multiple storage profiles using the `for_each` loop to an existing VMC account/region, the storage profiles show up in different tiles like they belong to different regions and all of them are marked as default, which is abnormal because only 1 profile can be default for a single region.

**To Reproduce**
1. Manually add a VMC account and zone to vRA.
2. Create Terraform config for managing multiple storage profiles for a single region. See the [example](https://gist.github.com/brude-softserve/98620847f792afb921b6a6fea61b2012).
3. Run `terraform apply`.
4. The storage profiles that have been created show up as different tiles on the Storage Profiles dashboard.

**Expected behavior**
Storage profiles for a single region should show up in a single tile in the Storage Profiles dashboard and only one of them can be default.

**Screenshots**
![image](https://user-images.githubusercontent.com/63772754/116719467-c607c380-a9e3-11eb-8278-8de409e5ad73.png)

**Comment by wilsonandvmware** [comment]
This is a bug from the API side, I have opened an internal bug for the storage team. I will update this thread once the bug is fixed from the vRA side. In the mean time, you can use postman API to create multiple storage profiles in consecutive order as a workaround. Please let me know if you have more questions.

**Comment by wilsonandvmware** [comment]
Based on the comments from the API team, `Creation of Storage Profile should never be done using concurrent calls. The service is not capable of handling parallel requests.` But if there are any existing profiles then it should handle concurrent requests. As a workaround I think you can manually create one storage profiles first before sending concurrent creation calls. Or you can run all the request in sequential order.

**Comment by brude-softserve** [comment]
> Based on the comments from the API team, `Creation of Storage Profile should never be done using concurrent calls. The service is not capable of handling parallel requests.` But if there are any existing profiles then it should handle concurrent requests. As a workaround I think you can manually create one storage profiles first before sending concurrent creation calls. Or you can run all the request in sequential order.

Thanks for the clarification! Though it's not very good from the IaaC point of view... Could you add some examples to the repo about how to create multiple storage profiles in sequential order with Terraform?

**Comment by wilsonandvmware** [comment]
@brude-softserve  I agree some optimization could have been done from the IaaS api side. I think for terraform all resource creation will be in concurrent order unless there are dependency. When I test locally I tried to add two profiles and one depends on the other and then set a timeout for 10 second, which will avoid this issue, but I don't think it would be a good example for that. 

One suggestion I got from the API team is to create the first profile manually, and then the rest of the profiles can be created in concurrent order once we have the first profile created(same zone). Could you try this approach please?

**Comment by rajmalds** [comment]
Still this issue is not resolved..
