### ISSUE TITLE
terraform refresh returns outputs after terraform destroy

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#336]
**vRA version**
vRealize Automation 8.4.0.16324 (17874359)

**Terraform version**
Terraform v0.14.8

**terraform-provider-vra plugin version**
+ provider registry.terraform.io/vmware/vra v0.3.5

**Describe the bug**
I created a terraform module for new project.  I destroyed using `terraform destroy`.  When I run `terraform output` I get `Warning: No outputs found` per design.  However, when I run `terraform refresh`, I get outputs.

**To Reproduce**
1. Terraform config file (for updates, config file before applying the change and the change made)
```hcl
resource "vra_project" "this" {
  name        = var.project_name
  description = var.project_description

  dynamic "zone_assignments" {
    for_each = data.vra_zone.this
    content {
      zone_id          = zone_assignments.value.id
      priority         = 1
      max_instances    = 0
      cpu_limit        = var.cpu_limit
      memory_limit_mb  = var.memory_limit_mb
      storage_limit_gb = var.storage_limit_gb
    }
  }

  shared_resources  = var.share_resources
  administrators    = var.administrators
  members           = var.members
  viewers           = var.viewers

}

output project_name {
  value = vra_project.this.*.name
}
output cloud_zones {
  value = values(data.vra_zone.this)[*]["name"]
}
```

2. Terraform command

- terraform init
- terraform apply 
- terraform destroy
- terraform output
- terraform refresh

3. Error

**Expected behavior**
May be it should return warning that resource doesn't exist?

**Screenshots**

**Logs**
Will attach logs if required.

**Desktop (please complete the following information):**
 - OS: Windows 10
 
**Additional context**

**Comment by wilsonandvmware** [comment]
@VickyWinner  Do you still see this error ? I am not able to reproduce it. I got the following messages after repeating the terraform commands
```
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.
```

**Comment by VickyWinner** [comment]
I still see it.

`PS /data> terraform refresh`
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.


Outputs:

cloud_zones = [
  "us-east-1b",
]
project_name = [
  "12345-abcProject",
]

`PS /data> terraform version`
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/vmware/vra v0.3.6

Your version of Terraform is out of date! The latest version
is 1.0.1. You can update by downloading from https://www.terraform.io/downloads.html

`outputs.tf`
output "project_name" {
  value = module.example-project.project_name
}

output "cloud_zones" {
  value = module.example-project.cloud_zones
}

**Comment by wilsonandvmware** [comment]
@VickyWinner  What do you see from the console after applying `terraform destroy`  For me I see something like

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # vra_project.this will be destroyed
  - resource "vra_project" "this" {
      - administrators    = [] -> null
      - custom_properties = {} -> null
      - id                = "005fe03c-1ca4-45a5-b34b-f42bbba7bf98" -> null
      - members           = [] -> null
      - name              = "test" -> null
      - operation_timeout = 0 -> null
      - shared_resources  = true -> null
      - viewers           = [] -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Changes to Outputs:
  - project_name = [
      - "test",
    ] -> null

Do you really want to destroy all resources?
```

**Comment by VickyWinner** [comment]
Yes @wilsonandvmware,  I see similar message.

```
  # vra_project.this[0] will be destroyed
  - resource "vra_project" "this" {
      - administrators    = [] -> null
      - custom_properties = {} -> null
      - description       = "Project description" -> null
      - id                = "4ec68d89-f3bc-4ec8-a29b-837a49223354" -> null
      - members           = [] -> null
      - name              = "12345-abcProject" -> null
      - operation_timeout = 6000 -> null
      - shared_resources  = true -> null
      - viewers           = [] -> null

      - zone_assignments {
          - cpu_limit        = 32 -> null
          - max_instances    = 2 -> null
          - memory_limit_mb  = 819200 -> null
          - priority         = 1 -> null
          - storage_limit_gb = 0 -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Changes to Outputs:
  - cloud_zones  = [
      - "us-east-1b",
      - "us-east-2a",
    ] -> null
  - project_name = [
      - "12345-abcProject",
    ] -> null
```

`PS /data> terraform refresh`
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.

```
Outputs:

cloud_zones = [
  "us-east-1b",
  "us-east-2a",
]
project_name = [
  "12345-abcProject",
]

**Comment by wilsonandvmware** [comment]
I think this is a terraform issue, not from the vRA provider side. I can only reproduce it once I upgrade my terraform version from 0.13 to 0.14

I opened an issue on the terraform repo and they confirmed the above behavior is related to the recent changes made to the `terraform refresh` command, FYI  https://github.com/hashicorp/terraform/issues/29166
