### ISSUE TITLE
vra_region documentation under Data Source is blank

### ISSUE THREAD

**Issue by martin9700** [vmware/terraform-provider-vra#339]
**Describe the bug**
vra_region documentation under Data Source is blank

**To Reproduce**
https://registry.terraform.io/providers/vmware/vra/latest/docs/data-sources/region

**Expected behavior**
Something probably should be written there

**Comment by Prativa20** [comment]
Added doc fir this https://github.com/vmware/terraform-provider-vra/pull/366
