### ISSUE TITLE
Need ability to add a specific catalog item to a new project and not the whole source

### ISSUE THREAD

**Issue by mars4life** [vmware/terraform-provider-vra#345]
vRA version : 8.3
Terraform version 0.14.4
terraform-provider-vra plugin version : 0.3.6

**Is your feature request related to a problem? Please describe.**
We can add a whole catalog source to a new project using catalog_source_entitlement but my need is to add a specific catalog item (not all blueprints for example , but a specific one)

**Describe the solution you'd like**
Add a new resource (catalog_item_entitlement)

**Comment by mars4life** [comment]
Pull request #346

**Comment by tenthirtyam** [comment]
@mars4life Have you had a chance to look at your pull request and resolve the CL requirements?

Ryan

**Comment by tenthirtyam** [comment]
PR https://github.com/vmware/terraform-provider-vra/pull/420
