### ISSUE TITLE
Ability to terraform import for storage similar to  vra_fabric_network_vsphere

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#353]
vRA version
 8.5
Terraform version
     Terraform v0.14.8

terraform-provider-vra plugin version
     provider registry.terraform.io/vmware/vra v0.3.6

**Is your feature request related to a problem? Please describe.**
Don't see a terraform resource for a vra Storage  object. Need to be able to update it (for example, applying tags) like you can using the vra_fabric_network_vsphere resource. 

- support for terraform import for storage object
- terraform resource so it can be managed for day2 after import.

**Describe the solution you'd like**
A terraform resource to manage storage object similar to vra_fabric_network_vsphere.

**Describe alternatives you've considered**
None identified.

**Additional context**

**Comment by frodenas** [comment]
The IaaS API does not implement a `PATCH` operation for the `Fabric vSphere Datastore` resources. I've opened an internal enhancement request. We will add it to the provider once it is supported in IaaS API.

**Comment by VickyWinner** [comment]
@frodenas How is that internal enhancement request being tracked?  should we keep this issue open until then?  if we keep it open,  the bot will again close it as stale after a month.

**Comment by frodenas** [comment]
@VickyWinner Let's keep it open. We've adjusted the bot to only close issues that have certain labels:

https://github.com/vmware/terraform-provider-vra/blob/0b239900ee3019d70fc1e1fe2e65d88626f97b87/.github/workflows/stale.yml#L17
