### ISSUE TITLE
provider doesn't remove/add user permissions at the same time.

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#360]
**vRA version**
vRealize Automation 8.4.0.16324 (17874359)

**Terraform version**
Terraform v0.14.8

**terraform-provider-vra plugin version**
+ provider registry.terraform.io/vmware/vra v0.3.8

**Describe the bug**
I am creating a project and adding users for administrators/members/viewers.  Initially I added 2 administrator users. After applying, now I remove one user and add another user.  When I run `terraform plan`, I see that one will be removed and one will be added.  However, when I run terraform apply, it only adds user but doesn't remove.  When I run terraform plan/apply again, it removes the user now.

**To Reproduce**
```hcl
resource "vra_project" "this" {
  count       = var.project_count
  name        = var.project_name
  description = var.project_description

  administrator_roles {
    email = "user1@vra.local"
    type = "group"
  }

  administrator_roles {
    email = "user2@vra.local"
    type = "group"
  }

/*  administrator_roles {
    email = "user3@vra.local"
    type = "group"
  }
*/
  operation_timeout = var.operation_timeout //6000
}

Steps to reproduce the behavior:
1. using above config, run terraform plan/apply
2. comment 2nd `administrator_roles` block and uncomment 3rd block of code.
3. run terraform plan/apply
4. you will see that user3 was added but user2 wasn't removed.
5. run terraform plan/apply again and see that user2 is now removed.

**Expected behavior**
I should be able to add and remove users at once.

**Comment by dondon3345678** [comment]
Based on the design and implementation of IAAS API to update administrators/members/viewers, it's not capable to add and remove users roles in a single request.

**Comment by tenthirtyam** [comment]
If there is a limitation in the IaaS API, the following should be considered:

- Spawn a docs issue to update the [argument reference](https://registry.terraform.io/providers/vmware/vra/latest/docs/resources/vra_project#argument-reference) regarding this limitation.
- Update the [example](https://github.com/vmware/terraform-provider-vra/blob/master/examples/project/main.tf) as it would be misleading in demonstrating the use of both in a single plan.

```
administrator_roles {
    email = "jason@vra.local"
    type = "user"
  }

administrator_roles {
    email = "jason-group@vra.local"
    type = "group"
  }
```

- Product (vRA IaaS API) feature enhancement  to address the limitation.

Ryan

**Comment by dondon3345678** [comment]
Updated the resource page and provided an example in https://github.com/vmware/terraform-provider-vra/pull/367. Close this issue

**Comment by VickyWinner** [comment]
The suggestion you mentioned in the [docs](https://registry.terraform.io/providers/vmware/vra/latest/docs/resources/vra_project#argument-reference) doesn't work in automation pipeline.  We cannot customize pipeline to handle the limitations in IaaS API.  The other alternate you can suggest is perform 1 action/request at a time.  Can we have this included as option 2.?

**Comment by rnelson0** [comment]
Before opening another ticket on this, is the limitation that IaaS API can only perform one of add/delete in a single request also a limit in the terraform provider, or is it possible for terraform to make two requests when it detects an add and a delete? I don't know terraform provider limitations enough and if that's a hard limitation, no reason to track a new issue. Thanks.
