### ISSUE TITLE
Error: context deadline exceeded when creating cloud account in vra8.4

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#362]
vRA version
vRealize Automation 8.4.1.16947 (18054500)

Terraform version
Terraform v0.14.8

terraform-provider-vra plugin version
+ provider registry.terraform.io/vmware/vra v0.3.8

Per @dmettem opening a new issue for [246](https://github.com/vmware/terraform-provider-vra/issues/246)

**Comment by VickyWinner** [comment]
Additionally, I found another issue. While nearing the timeout (which I believe is 60 seconds), request is already sent to create cloud account and then the timeout happens.  By the time I retry, there will already be an account created and terraform throws below error message.

```
Error: [POST /iaas/api/cloud-accounts-vsphere][400] createVSphereCloudAccountBadRequest  &{Message:Cloud 
account name must be unique StatusCode:400}

  on main.tf line 12, in resource "vra_cloud_account_vsphere" "testvCloud":
  12: resource "vra_cloud_account_vsphere" "testvCloud" {
```

Please consider above behavior when making necessary changes.  I would prefer the `timeout` feature to be available as a configurable meta argument.

Thanks

**Comment by tenthirtyam** [comment]
I see this as an optional provider configuration that could used to override for the default 60s timeout.

```
variable "vra_url" {
  type        = string
  description = "The base URL of the vRealize Automation endpoint. (e.g. https://cloud.rainpole.io)"
}

variable "vra_refresh_token" {
  type        = string
  description = "Refresh API token from the vRealize Automation endpoint."
  sensitive   = true
}

variable "vra_insecure" {
  type        = bool
  description = "Set to true for self-signed certificates."
  default     = false
}

variable "vra_timeout_override" {
  type        = number
  description = "Override the default timeout."
  default     = 120
}

provider "vra" {
  url              = var.vra_url
  refresh_token    = var.vra_refresh_token
  insecure         = var.vra_insecure
  timeout_override = var.vra_timeout_override
}
```

**Comment by VickyWinner** [comment]
@tenthirtyam,  I did a search for this meta argument and couldn't find anywhere in document or in the go code.  did you test this working?  When I tried it with below configuration,

```hcl
provider "vra" {
  url           = "https://${var.vra_host}"
  refresh_token = var.refresh_token
  insecure      = var.insecure
  timeout_override = 500
}
```

I get below error like this.

```log
Error: Unsupported argument

  on providers.tf line 15, in provider "vra":
  15:   timeout_override = 500

An argument named "timeout_override" is not expected here.

**Comment by tenthirtyam** [comment]
No, this is more of a theoretical scenario of what it could look like when implemented - not an actual today.

**Comment by frodenas** [comment]
The cloud-account creation is now using asynchronous calls (merged at #421), after we send the POST request, we get a request tracker, and we periodically refresh the tracker status until the backend request has finished. This will alleviate the problem that you're experiencing. This will be available in the next release of the provider.

**Comment by tenthirtyam** [comment]
Very nice, Ferran!

**Comment by frodenas** [comment]
This has been delivered in [v0.5.0](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.5.0).
