### ISSUE TITLE
Provider version 0.3.9 is not available in the terraform registry

### ISSUE THREAD

**Issue by rnelson0** [vmware/terraform-provider-vra#370]
The latest version at https://registry.terraform.io/providers/vmware/vra/latest/docs is 0.3.8. 0.3.9 has been published on github but not available on the registry. Please publish it there.

**Comment by markpeek** [comment]
Thanks for noticing. I put another request in for HashiCorp to sync the artifacts to the registry.

**Comment by markpeek** [comment]
@rnelson0 @tenthirtyam v0.3.9 has been pulled to the registry.

**Comment by rnelson0** [comment]
Thank you!
