### ISSUE TITLE
Update vmware/terraform-provider-vra repository settings.

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/terraform-provider-vra#374]
**vRA version**
Not applicavle.

**Terraform version**

Not applicable.

**terraform-provider-vra plugin version**

Not applicable.

**Describe the bug**

Please update the settings for the repository to conform with other Terraform provider repositories:

**Description**: "Terraform VMware vRealize Automation provider"

**Website**: `https://registry.terraform.io/providers/vmware/vra/`

**Topics**: `terraform` `terraform-provider` `vra`

**To Reproduce**

Not applicable.

**Expected behavior**

Not applicable.

**Screenshots**

Not applicable.

**Logs**

Not applicable.

**Desktop (please complete the following information):**

Not applicable.

**Additional context**

None

**Comment by tenthirtyam** [comment]
+ @markpeek 🙃

**Comment by frodenas** [comment]
Done!

**Comment by tenthirtyam** [comment]
Thank you, Ferran!
