### ISSUE TITLE
Create Code Stream Variables

### ISSUE THREAD

**Issue by saintdle** [vmware/terraform-provider-vra#400]
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [X] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### Description
Ability to create variables for Code Stream using the provider. Potentially secrets could be pulled from hashicorp vault in the HCL files. 

### Describe alternatives you've considered
Creating a script which uses API calls to create variables in a repeatable fashion. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by frodenas** [comment]
Code Stream is being deprecated. Closing this issue.
