### ISSUE TITLE
resource - vra_zone - compute_ids - type mismatch

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#404]
### vRA Version
vRealize Automation 8.4.1.16947 (18054500)

### Terraform Version
Terraform v1.0.6

### vRA Terraform Provider Version
+ provider registry.terraform.io/vmware/vra v0.4.0

### Affected Resource(s)
* `vra_zone`

### Terraform Configuration Files

```hcl
resource "vra_zone" "this" {
  name        = var.name
  description = var.description
  region_id   = var.region_id
  compute_ids = [
    "9cf2ebbe44410b844ebc9f9bc5ccbf8d3916ff40",
    "5a9e21c76882dffe2ed5effb6318797f884f1344",
    "933b71d70484cddeaed53ad7c2d27c748beede6c",
    "8d3e43265a080c68845ef5dde93b6f6ead204266",
  ]
}
```

### Expected Behavior
terraform should create vra_zones and attach the compute_ids passed as list per [documentation](https://registry.terraform.io/providers/vmware/vra/latest/docs/resources/vra_zone#compute_ids).

### Actual Behavior
 Invalid value for "v" parameter: cannot convert string to list of any single type.

### Screenshots
not applicable

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by frodenas** [comment]
@VickyWinner I'm unable to reproduce your issue. Can you please paste the sanitized debug output? (or GitHub Gist or send it to me at `rodenasf` at VMware). Thanks!

**Comment by VickyWinner** [comment]
> @VickyWinner Yes, I used a list of compute ids. For reference, this is what I just used to test it:
> 
> ```
> data "vra_cloud_account_vsphere" "vsphere" {
>   name = "vsphere"
> }
> 
> data "vra_region" "vsphere" {
>   cloud_account_id = data.vra_cloud_account_vsphere.vsphere.id
>   region           = "my-datacenter"
> }
> 
> data "vra_fabric_compute" "cluster3" {
>   filter = "name eq 'Cluster03'"
> }
> 
> data "vra_fabric_compute" "cluster4" {
>   filter = "name eq 'Cluster04'"
> }
> 
> data "vra_fabric_compute" "cluster5" {
>   filter = "name eq 'Cluster05'"
> }
> 
> resource "vra_zone" "this" {
>   name        = "test-compute-ids"
>   description = "test zone"
>   region_id   = data.vra_region.vsphere.id
>   compute_ids = [
>       data.vra_fabric_compute.cluster3.id,
>       data.vra_fabric_compute.cluster4.id,
>       data.vra_fabric_compute.cluster5.id
>   ]
> }
> ```

@frodenas  does the last line of the list element has no comma?  my result returns list with comma in the last element.

**Comment by frodenas** [comment]
It does not matter (this should be parsed by terraform hcl parser before being sent to the provider). Anyway, I've tried with and without a comma in the last element with the same (successful) result.

Are you sure there's nothing else in the terraform file that contains a `v` parameter? That message (`Invalid value for "v" parameter`) is suspicious. Also, can you please try without the `compute_ids` property? I want to be sure that the error happens when parsing the compute_ids and not somewhere else.

**Comment by frodenas** [comment]
Specifically, do you have any [tolist](https://www.terraform.io/docs/language/functions/tolist.html) function in your tf files?

**Comment by VickyWinner** [comment]
> It does not matter (this should be parsed by terraform hcl parser before being sent to the provider). Anyway, I've tried with and without a comma in the last element with the same (successful) result.
> 
> Are you sure there's nothing else in the terraform file that contains a `v` parameter? That message (`Invalid value for "v" parameter`) is suspicious. Also, can you please try without the `compute_ids` property? I want to be sure that the error happens when parsing the compute_ids and not somewhere else.

@frodenas I have successful result when I don't use `compute_ids`.  If it works with and without comma, then I will re-try and share the debug info.  

Thanks
