### ISSUE TITLE
project "Placement policy" via vra_project resource

### ISSUE THREAD

**Issue by fmosti** [vmware/terraform-provider-vra#414]
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [x] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### Description
When creating a project we would like to set the "Placement policy" to "SPREAD" via the vra_project resource

### Describe alternatives you've considered
Manually change Placement policy after the project creation via the vra_project terraform resource

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by frodenas** [comment]
This enhancement been added at #416.
