### ISSUE TITLE
vra_project shared_resources = false not configured on project

### ISSUE THREAD

**Issue by chunkyen** [vmware/terraform-provider-vra#438]
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [x] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### vRA Version

vRA 8.8
### Terraform Version

1.1.9
### vRA Terraform Provider Version

0.5.1
### Affected Resource(s)

vra_project
### Terraform Configuration Files

shared_resources = false
```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

The settings for "Deployments are shared between all users in the project" should be unchecked.
### Actual Behavior

The settings for "Deployments are shared between all users in the project"  are not unchecked.
### Steps to Reproduce

After running terraform apply with the above parameters and value, the GUI on vRA still shows "Deployments are shared between all users in the project" even though it says the settings will be changed in the terraform apply output. See below

>  vra_project.this will be updated in-place
>  ~ resource "vra_project" "this" {
>       id                      = "c7855a2c-0dab-4a6a-98aa-878b941a310c"
>        name                    = "Myproject1"
>      ~ shared_resources        = true -> false
>        # (7 unchanged attributes hidden)

>        # (3 unchanged blocks hidden)
>   }
>
>Plan: 0 to add, 1 to change, 0 to destroy.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by frodenas** [comment]
There was a bug at the [vra-sdk-go](https://github.com/vmware/vra-sdk-go), this has been solved at #468
