### ISSUE TITLE
data var_image arguments

### ISSUE THREAD

**Issue by gsbagga** [vmware/terraform-provider-vra#441]
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [ ] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### vRA Version

8.7

### Terraform Version

1.1.7

### vRA Terraform Provider Version

0.5.1

### Affected Resource(s)

var_image 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
```
data "vra_image" "rhel7" {
  id = var.rhel7_ami
}

### Expected Behavior

retrieve image name by providing ami id of the image

### Actual Behavior

Error: Missing required argument
As per the documentation I should be able to pass only ID as the argument. 
https://registry.terraform.io/providers/vmware/vra/latest/docs/data-sources/vra_image

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
Filter is a **required** argument.

https://github.com/vmware/terraform-provider-vra/blob/a2313c06166fcf492349683e382ba4b349be645a/vra/data_source_image.go#L15-L18

Ideally, the documentation should reflect it an attribute is required or optional as well as update the inaccurate example.

Recommend this for docs updates. @frodenas I'd be happy to PR this one of you like.

Example with the use of `filter`:

https://github.com/tenthirtyam/terrafom-examples-vmware/blob/main/vra/vra-image-mapping/main.tf


**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by gsbagga** [comment]
Ryan,

Thanks for sharing the example and asking for docs to be updated to reflect this. 

Is it possible for you to add an example of adding a network profile for AWS and Azure? It will be very helpful.

**Comment by tenthirtyam** [comment]
Hi, @gsbagga 👋 

I'll submit a PR next week to resolve the concern in the docs for this resource.

For your other request, please [submit an issue](https://github.com/tenthirtyam/terrafom-examples-vmware/issues) on my personal project and I'll work on adding some additional examples for hyperscalers.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Pull request has been GH-442 submitted for review, @frodenas. 😄 

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
