### ISSUE TITLE
Unable to apply tag block to Azure Cloud Account

### ISSUE THREAD

**Issue by bohleadam** [vmware/terraform-provider-vra#443]
The creation of a  "vra_cloud_account_azure" resource doesn't seem to be able to apply a tag block to the Cloud Account

```
resource "vra_cloud_account_azure" "azure_cloud_account" {
  name            = var.azure_account_name
  description     = var.azure_description
  subscription_id = var.azure_subscription_id
  tenant_id       = var.azure_tenant_id
  application_id  = var.azure_application_id
  application_key = var.azure_application_key
  regions         = var.azure_regions
  
  tags {
    key   = "cloud"
    value = "azure"
  }

}
```

running the above fails to assign the capability tags to the Cloud Account in Cloud Assembly. AWS and GCP Cloud Accounts don't have this issue

**Comment by tenthirtyam** [comment]
Interestingly, the `
r/vra_cloud_account_azure
` has the same inclusion of the `tagsSchema` in the resource schema

```go
"tags": tagsSchema(),
```

as well as use in the resource creation...

```go
Tags:               expandTags(d.Get("tags").(*schema.Set).List()),

```

as the other Cloud Account resources.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by frodenas** [comment]
I just tested this use-case on a vRA 8.9.0 instance and I see the capability tags applied to my azure cloud account.

@bohleadam Which version of vRA are you using? do you have any debug logs so we can check the API calls?
