### ISSUE TITLE
Data Source: vra_image documentation incorrect/add support to lookup images by ID

### ISSUE THREAD

**Issue by robertito121** [vmware/terraform-provider-vra#444]
Documentation for the Data Source: vra_image https://registry.terraform.io/providers/vmware/vra/latest/docs/data-sources/vra_image says you can look up images by ID; however ID is a computed attribute on this data source as shown in the latest tag 0.5.2 as well as the tag corresponding to the documentation 0.5.1 https://github.com/vmware/terraform-provider-vra/blob/v0.5.1/vra/data_source_image.go#L28. IT would be nice that instead of fixing the documentation, support is also added to look up images by ID besides using filter.

**Comment by tenthirtyam** [comment]
This should be split into two issues. 

1. Documentation issue for correction of the data source docs. (priority).
2. Enhancement issue requesting for lookup by ID for the data source.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
