### ISSUE TITLE
[Doc] Resource: vra_cloud_account_vsphere references incorrect argument for dcid

### ISSUE THREAD

**Issue by GaryJBlake** [vmware/terraform-provider-vra#450]
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [x] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### vRA Version
vRA Cloud

### Terraform Version

Terraform v1.2.4

+ provider registry.terraform.io/hashicorp/vsphere v2.2.0
+ provider registry.terraform.io/vmware/vra v0.5.1

Your version of Terraform is out of date! The latest version
is 1.2.5. You can update by downloading from https://www.terraform.io/downloads.html

### vRA Terraform Provider Version

+ provider registry.terraform.io/hashicorp/vsphere v2.2.0
+ provider registry.terraform.io/vmware/vra v0.5.1

### Affected Resource(s)

vra_cloud_account_vsphere

### Expected Behavior

Should not error

### Steps to Reproduce

Create a terraform plan using:

dc_id = var.data_collector_name

instead of:

dcid = var.data_collector_name

<img width="846" alt="image" src="https://user-images.githubusercontent.com/31245616/179544499-a0800af2-8d36-4407-81d0-5fdfa0bff9fc.png">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@frodenas - it seems that `r/cloud_account_vsphere` implemented the schema with `dcid` whereas the other relevant accounts (NSXv, NSX-T, and VMC) use `dc_id` in the schema. That is somewhat confusing and prone to error - perhaps it would be best to transition it to `dc_id`?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
