### ISSUE TITLE
Remove deprecated API Usage (Catalog Entitlements)

### ISSUE THREAD

**Issue by the-vas** [vmware/terraform-provider-vra#498]
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [x] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### Description
Please Update the API Usage for Catalog Entitlements.

### Describe alternatives you've considered
Currently a deprecated API Path is used for Catalog Entitlements. With vRA 8.8 Entitlements should be created via Content Sharing Policy (/policy/api/policies).
The Problem we are currently facing with the usage of the deprecated API is, that the defined state is not fully applied to the system leading to a configuration drift and manual clean up.

### References
Code:
https://github.com/vmware/vra-sdk-go/blob/46d819a2bf81fd75b3d97342accc879939ae3050/pkg/client/catalog_entitlements/catalog_entitlements_client.go#L55C24-L55C55

VMWare Ticket Reference:
SR 23449444007

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by frodenas** [comment]
The old **vra_catalog_item_entitlement** and **vra_catalog_source_entitlement** data source and resource have been deprecated in favor of a new **vra_content_sharing_policy** data source and resource.
