### ISSUE TITLE
vra_image_profile always changes when more than one image in a mapping

### ISSUE THREAD

**Issue by pgsmith123** [vmware/terraform-provider-vra#539]
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [x] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### vRA Version

vRA 8.13

### Terraform Version

1.9.3

### vRA Terraform Provider Version

0.10.0

### Affected Resource(s)

vra_image_profile

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
```
resource "vra_image_profile" "server_2022_gui_az1" {
  name        = "server_2022_gui"
  region_id   = data.vra_region.AZ1.id

  image_mapping {
    name     = "server_2022_gui"
    image_id = data.vra_image.server_2022_gui_az1.id
  }
}

resource "vra_image_profile" "server_2022_gui_az2" {
  name        = "server_2022_gui"
  region_id   = data.vra_region.AZ2.id

  image_mapping {
    name     = "server_2022_gui"
    image_id = data.vra_image.server_2022_gui_az2.id
  }
}

### Expected Behavior

Should find no changes to the plan on subsequent applies

### Actual Behavior

Wants to change the infrastructure at every apply. Plan: 0 to add, 2 to change, 0 to destroy.

### Steps to Reproduce

run a subsequent apply

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pgsmith123** [comment]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:        
  ~ update in-place

Terraform will perform the following actions:

  # vra_image_profile.server_2022_gui_az1 will be updated in-place
  ~ resource "vra_image_profile" "server_2022_gui_az1" {
        id                 = "80948167-4bc2-4bb5-ae6e-828bea7edb81-b101f148-5871-43b3-96bf-f070dd59c2a1"
        name               = "server_2022_gui"
        # (6 unchanged attributes hidden)

      - image_mapping {
          - description        = "hosting_server_2022_gui_az1" -> null
          - external_id        = "50076391-72cc-1649-34fe-aa87513c794f" -> null
          - external_region_id = "Datacenter:datacenter-21" -> null
          - image_id           = "0efdf212ea2780cbe071b16a5ba26f72fb80222e" -> null
          - image_name         = "hosting_server_2022_gui_az1" -> null
          - name               = "server_2022_gui" -> null
          - os_family          = "WINDOWS" -> null
          - private            = false -> null
            # (3 unchanged attributes hidden)
        }
      + image_mapping {
          + description        = (known after apply)
          + external_id        = (known after apply)
          + external_region_id = (known after apply)
          + image_id           = "0efdf212ea2780cbe071b16a5ba26f72fb80222e"
          + name               = "server_2022_gui"
          + organization       = (known after apply)
          + os_family          = (known after apply)
          + owner              = (known after apply)
          + private            = (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

  # vra_image_profile.server_2022_gui_az2 will be updated in-place
  ~ resource "vra_image_profile" "server_2022_gui_az2" {
        id                 = "80948167-4bc2-4bb5-ae6e-828bea7edb81-e54ff1c3-55fc-425c-a522-21b3aeaa5805"
        name               = "server_2022_gui"
        # (6 unchanged attributes hidden)

      - image_mapping {
          - description        = "hosting_server_2022_gui_az2" -> null
          - external_id        = "5007a1e7-b716-ad10-4cf4-d5c1b61de5ad" -> null
          - external_region_id = "Datacenter:datacenter-26" -> null
          - image_id           = "73d21b87ed40276739cfe39038302ad222d30f28" -> null
          - image_name         = "hosting_server_2022_gui_az2" -> null
          - name               = "server_2022_gui" -> null
          - os_family          = "WINDOWS" -> null
          - private            = false -> null
            # (3 unchanged attributes hidden)
        }
      + image_mapping {
          + description        = (known after apply)
          + external_id        = (known after apply)
          + external_region_id = (known after apply)
          + image_id           = "73d21b87ed40276739cfe39038302ad222d30f28"
          + name               = "server_2022_gui"
          + organization       = (known after apply)
          + os_family          = (known after apply)
          + owner              = (known after apply)
          + private            = (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 2 to change, 0 to destroy.

**Comment by frodenas** [comment]
The main issue is the nested structure used for the mappings, which is not well supported in older versions of the Terraform SDK (see [discussion](https://discuss.hashicorp.com/t/typeset-is-not-picking-up-correct-changes/23735/2)). We need to switch to the new [Terraform Plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework), which has better support for complex/nested structures like the ones used on the `vra_image_profile` resource. This upgrade is not easy, and we haven't had the bandwidth to implement this change yet.

The same issue was reported at #358. I'm going to close this as a duplicate. Please reopen if you think this is a different issue.
