### ISSUE TITLE
CloudInit 

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#74]
This is more of a question.  Is there a way in vra_machine to pass cloud init info?
In blueprints cloudinit can be passed, not sure if i have seen a way to pass cloud init via the terraform provider.

We are using cloud init to name machines, set ip address instead of using customization specs since only one or the other can be used.   Also we are allowing users to use their own cloud init files to run after their  VMs are created.

**Comment by dmettem** [comment]
@mdittbrenner215 You can use the `boot_config` argument in `vra_machine` to pass cloud init info.

Here's an example:

`resource "vra_machine" "this" {
    name   = "terraform_vra_wordpress"
    image  = "ubuntu"
    flavor = "small"

    boot_config {
      content = <<EOF
#cloud-config
repo_update: true
repo_upgrade: all

packages:
- apache2

runcmd:
- service apache2 reload
EOF
  }
}`

Let me know how it goes.

**Comment by mdittbrenner215** [comment]
Awesome.  I thought it was that after looking at the vra_machine document but couldnt get the format correct.

**Comment by mdittbrenner215** [comment]
ty for info . This is what i needed for documentation. I am not seeing it being executed but we have a similar issue open so we can track through that issue.
