### ISSUE TITLE
vRA Select & Use Storage Profiles

### ISSUE THREAD

**Issue by chrisd27519** [vmware/terraform-provider-vra#76]
Disk and Storage profile syntax and formatting documentation is non existent. As with the networks, please give us an example usage to select and use storage profiles

**Comment by AnjaliMangal** [comment]
This a documentation enhancement and should be available by end of month . 11/27

**Comment by dark2phoenix** [comment]
Following up on this open request, I don't see an example for storage profiles.  Can you point me to the example that covers this?

**Comment by dmettem** [comment]
@Prativa20 - Do you happen to have the example already?

**Comment by Prativa20** [comment]
There is no documentation yet, I will add it by the end of this week.
