### ISSUE TITLE
vRA image map clodconfig not executing

### ISSUE THREAD

**Issue by chrisd27519** [vmware/terraform-provider-vra#77]
When using vRA image maps for the machine resource, we are finding that any cloud-config attached to the image (not in the terraform yaml) is being ignored, i.e. not executed. This seems to be true for cloud-init and cloudbase-init.

**Comment by markpeek** [comment]
Likely will need more information on how to reproduce. Using a Photon image imported into vCenter Content Library, I'm able to see cloud-config running from both the image profile and machine. In other words, these resources work as expected to create two files in /root:
```
resource "vra_image_profile" "this" {
  name        = "cloud-config-test-image-profile"
  region_id   = data.vra_region.this.id

  image_mapping {
    name       = "photon"
    image_id = "3f3e71ca89f494d4da54f59c2116160a0afdbb62"
    cloud_config = <<EOF
#cloud-config
  runcmd:
    - sudo echo "foobar" > /root/foo
EOF
  }
}

resource "vra_machine" "this" {
  name        = "cloud-config-test-machine"
  project_id  = data.vra_project.this.id
  image       = "photon"
  flavor      = "medium"

  boot_config {
    content = <<EOF
#cloud-config
  runcmd:
    - echo "foobar" > /root/bar
EOF
  }
}
```

**Comment by mdittbrenner215** [comment]
I am not seeing cloudconfig being executed.  In this case its a windows box with cloud based init on it.

 boot_config {
      content = <<EOF

  #cloud-config
    - local-hostname: "tf-q1-${count.index}"
  runcmd:
    - New-Item -Path "C:\temp\" -Name "logfiles" -ItemType "directory"

  final_message: "The system is finally up, after $UPTIME seconds"
    EOF
  }

**Comment by mdittbrenner215** [comment]
I am not seeing a directory being created or any messages.

**Comment by markpeek** [comment]
Oh, Windows...got it. When you mentioned "cloud based init", do you mean this project, [Cloudbase-Init](https://cloudbase.it/cloudbase-init)? What version of Windows? Is this on vSphere or another cloud provider?

**Comment by mdittbrenner215** [comment]
We are supporting both windows and linux. I just happened to be trying this on Windows.  Yes Cloudbase-init. 

Windows 2019 on vsphere.

**Comment by markpeek** [comment]
I've never used this for initialization so I'll have to see about getting a Windows image with cloudbase-init on it to try this out. But I'm thinking the structure of the cloud config data is likely different for Windows and reading this [doc](https://cloudbase-init.readthedocs.io/en/latest/userdata.html).

**Comment by mdittbrenner215** [comment]
It looks like its running the cloudconfig that is associated with the image mapping but not merging the additional commands in the terraform.  Testing what happens if i remove image mapping cloud config and just run from terraform itself.

**Comment by markpeek** [comment]
BTW, I was able to look at the merged cloud config data by going into vCenter and looking at the VM vApp data to base64 decode the user-data property.

**Comment by mdittbrenner215** [comment]
TY for this.  I did check the vApp setting and it wasnt getting the merge, only the image cloud configuration.

**Comment by mdittbrenner215** [comment]
I have confirmed its a merge issue.  If i remove it from our image mapping the terraform cloud config comes through.

**Comment by botskowilson** [comment]
This is not a Terraform specific issue but related to how CloudInit works with Windows VM in vRA. This has been reported and is being tracked for the product itself.

**Comment by AnjaliMangal** [comment]
This fix will be  available in next vRA release . Its a vRA Product issue  .
