### ISSUE TITLE
404 Service error

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#78]
When running as a count we are getting a 404 for some of the machines being built.  In the case below I had a count of 7 machines.  2 of the machines errored with a Service not found: 404 NOT_FOUND " No matching handler" 

2019/10/24 12:52:32 [DEBUG] vra_machine.vms[4]: apply errored, but we're indicating that via the Error pointer rather than returning it: com.vmware.xenon.common.ServiceHost$ServiceNotFoundException: Service not found: 404 NOT_FOUND "No matching handler"
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/10/24 12:52:32 [TRACE] EvalMaybeTainted: vra_machine.vms[4] encountered an error during creation, so it is now marked as tainted
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/10/24 12:52:32 [TRACE] EvalWriteState: removing state object for vra_machine.vms[4]
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2019/10/24 12:52:32 [TRACE] EvalApplyProvisioners: vra_machine.vms[4] has no state, so skipping provisioners
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/10/24 12:52:32 [TRACE] EvalMaybeTainted: vra_machine.vms[4] encountered an error during creation, so it is now marked as tainted
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/10/24 12:52:32 [TRACE] EvalWriteState: removing state object for vra_machine.vms[4]
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalIf
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalIf
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalApplyPost
2019/10/24 12:52:32 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: com.vmware.xenon.common.ServiceHost$ServiceNotFoundException: Service not found: 404 NOT_FOUND "No matching handler"
2019/10/24 12:52:32 [ERROR] <root>: eval: *terraform.EvalSequence, err: com.vmware.xenon.common.ServiceHost$ServiceNotFoundException: Service not found: 404 NOT_FOUND "No matching handler"
2019/10/24 12:52:32 [TRACE] [walkApply] Exiting eval tree: vra_machine.vms[4]
2019/10/24 12:52:32 [TRACE] vertex "vra_machine.vms[4]": visit complete
2019/10/24 12:52:32 [DEBUG] vra_machine.vms[2]: apply errored, but we're indicating that via the Error pointer rather than returning it: com.vmware.xenon.common.ServiceHost$ServiceNotFoundException: Service not found: 404 NOT_FOUND "No matching handler"
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/10/24 12:52:32 [TRACE] EvalMaybeTainted: vra_machine.vms[2] encountered an error during creation, so it is now marked as tainted
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/10/24 12:52:32 [TRACE] EvalWriteState: removing state object for vra_machine.vms[2]
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2019/10/24 12:52:32 [TRACE] EvalApplyProvisioners: vra_machine.vms[2] has no state, so skipping provisioners
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/10/24 12:52:32 [TRACE] EvalMaybeTainted: vra_machine.vms[2] encountered an error during creation, so it is now marked as tainted
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/10/24 12:52:32 [TRACE] EvalWriteState: removing state object for vra_machine.vms[2]
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalIf
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalIf
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2019/10/24 12:52:32 [TRACE] <root>: eval: *terraform.EvalApplyPost
2019/10/24 12:52:32 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: com.vmware.xenon.common.ServiceHost$ServiceNotFoundException: Service not found: 404 NOT_FOUND "No matching handler"
2019/10/24 12:52:32 [ERROR] <root>: eval: *terraform.EvalSequence, err: com.vmware.xenon.common.ServiceHost$ServiceNotFoundException: Service not found: 404 NOT_FOUND "No matching handler"
2019/10/24 12:52:32 [TRACE] [walkApply] Exiting eval tree: vra_machine.vms[2]
2019/10/24 12:52:32 [TRACE] vertex "vra_machine.vms[2]": visit complete

**Comment by mdittbrenner215** [comment]
This is probably a vra error not a terraform issue, as vra is receiving the request and throwing an error.  I will be opening an issue with vra development.

**Comment by markpeek** [comment]
One way to see more debugging (but be careful of credential/info leak) of the API calls being use with return codes is to use these environment variables:

**Comment by mdittbrenner215** [comment]
thank you testing this now.

**Comment by mdittbrenner215** [comment]
I am still seeing same. Dont think this is on your end but can you keep this open for now but just awaiting response?  We are getting this directly with vra bu to look at this issue.

**Comment by botskowilson** [comment]
Yes, this is currently being tracked and investigated directly by the BU as it seems to be product, not Terraform related.

**Comment by mdittbrenner215** [comment]
I was asked to update with more information here so i will be adding a few comments so the BU can get more info on how i set it up and also that I was able to reproduce this multiple ways.

**Comment by mdittbrenner215** [comment]
provider "vra" {
  url           = "${var.url}"
  refresh_token = "${var.refresh_token}"
  insecure = "true"
}

data "vra_cloud_account_vsphere" "this" {
  name = "${var.cloud_account}"
}
data "vra_project" "this" {
  name = "${var.project}"
}


data "vra_network" "this" {
  name = "LS-96.118.196.16/28-2001:558:fc11:c::80/122"  
}

resource "vra_machine" "vms" {
  count = "${var.instance_count}"
  description = "terrafrom test machine"
  project_id  = "${data.vra_project.this.id}"
  image       = "Cloudbase-init"
  flavor      = "c5.large"
  name        = "tf-q1-${count.index}"
  nics {
      network_id = "${data.vra_network.this.id}"
  }
  tags {
    key   = "OS"
    value = "Windows"
  }
  timeouts {
    create = "20m"
    delete = "20m"
    update = "20m"
  }

  boot_config {
      content = <<EOF
  runcmd:
    - New-Item -Path "C:\temp\" -Name "logfiles" -ItemType "directory"
    EOF
  }

}

**Comment by dmettem** [comment]
I was able to repro this as well with a simple machine resource with count set to 10.

@mdittbrenner215 Feel free to add your comments and the multiple ways you were able to reproduce.

**Comment by mdittbrenner215** [comment]
instance_count if greater than 1 can trigger the 404. 

I have also seen this outside of the IAAS api using vra_deployment which is deploying via a blueprint from the API.

**Comment by mdittbrenner215** [comment]
If I use a count again there where there is MULTIPLE deployments (NOT multiple machines but deployments) I was getting the 404 plus sometimes other errors.

**Comment by dmettem** [comment]
@mdittbrenner215 Let's keep this issue for 404 errors seen with vra_machine resource.
It would be great if you can create another issue for the error seen with deployments.

**Comment by AnjaliMangal** [comment]
This fix is coming in next vRA product release in dec2019  - vRA 8.0.1

**Comment by mdittbrenner215** [comment]
Closing this issue. It is fixed in vra 8.0.1 and confirmed.
