### ISSUE TITLE
Provide pre-compiled releases

### ISSUE THREAD

**Issue by mdb** [vmware/terraform-provider-vra#79]
Offering users pre-compiled, cross-platform downloads of the provider published as immutable [GitHub releases](https://help.github.com/en/github/administering-a-repository/creating-releases) would be very useful.

I recognize that `terraform-provider-vra` is still under early-stage development and perhaps pre-compiled releases aren't yet viewed as warranted. Nonetheless, as a potential user testing the provider functionality, in my mind, this _could_...

* save me from having to compile the `terraform-provider-vra` from source code
* reduce the possibility that one user is using a `terraform-provider-vra` compiled from source code that differs from the source code used to compile a different user's `terraform-provider-vra`
* help developers and users better understand the state of bugs and features

The `terraform-provider-vinyldns` [releases here](https://github.com/vinyldns/terraform-provider-vinyldns/releases) offer an example of what I'm imagining.

Thanks!

**Comment by markpeek** [comment]
Thanks @mdb for pointing me to the vinyldns release code. I made it into a script and there is now a [v0.1.0 release](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.0) with binary artifacts for downloading.

**Comment by mdb** [comment]
Thank you @markpeek !
