### ISSUE TITLE
There does not appear to be a data source for Storage profiles

### ISSUE THREAD

**Issue by chrisd27519** [vmware/terraform-provider-vra#84]
There does not appear to be a data source for Storage profiles. Is there an alternate name in use to apply storage profiles to machine disks?

**Comment by dmettem** [comment]
WIP for vra_storage_profile data source.

**Comment by AnjaliMangal** [comment]
This should be available end of this week  11/22.

**Comment by Prativa20** [comment]
Added a data source for storage profile 
https://github.com/vmware/terraform-provider-vra/pull/111

However, it can only filter a storage profile by id. For example,
```
data "vra_storage_profile" "this" {
		id = vra_storage_profile.this.id
	}
```
Filtering by name is not available as the product do not support name filters. Opened a product bug. Once that is supported, the following will work

```
data "vra_storage_profile" "this" {
		filter = "name eq 'my-storage-profile-name'"
	}
```

**Comment by dmettem** [comment]
@Prativa20 - Can you please verify this as well?

**Comment by Prativa20** [comment]
As mentioned in my previous comment, we have the storage profile data source but it cannot be filtered by name at this point as this is not available in the product. I am closing this issue as it can be filtered by id and once filter by name is supported, I will update the issue and add it in the documentation.
