### ISSUE TITLE
Update disk device not remove disk

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#89]
I have added a second disk to a machine.
Remove the disk from the terraform file and run terraform apply.

   boot_config {
            content = "  runcmd:\n    - New-Item -Path \"C:\\temp\\\" -Name \"logfiles\" -ItemType 
  \"directory\"\n"
        }

      - disks {
          - block_device_id = "7f925b8589d816755962b18f7a420" -> null
          - name            = "disk2" -> null
        }

      nics {
            addresses          = []
            custom_properties  = {}
            device_index       = 0
            network_id         = "7f925b8589d816755962818e4c3a9"
            security_group_ids = []
        }

        tags {
            key   = "OS"
            value = "Windows"
        }

        timeouts {
            create = "20m"
            delete = "20m"
            update = "20m"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vra_machine.vms[0]: Modifying... [id=bd38273dc820eecf]
vra_machine.vms[0]: Modifications complete after 3s [id=bd38273dc820eecf]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

The disk is still attached to the VM and not removing it.

**Comment by dmettem** [comment]
@mdittbrenner215 Could you please share the config file for me to get started with troubleshooting this issue?

**Comment by mdittbrenner215** [comment]
So first run i ran it like:


provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure = "true"
}

data "vra_cloud_account_vsphere" "this" {
  name = var.cloud_account
}
data "vra_project" "this" {
  name = var.project
}

data "vra_network" "this" {
  name = "xxx.xxx.xxx.xxx"
  
}

 resource "vra_block_device" "vms" {
  capacity_in_gb =   500
 	name         =   "terraform_vra_block_device"
 	project_id    =   data.vra_project.this.id

}

resource "vra_machine" "vms" {
  count = "${var.instance_count}"
  description = "terrafrom test machine"
  project_id  = data.vra_project.this.id
  image       = "Cloudbase-init"
  flavor      = "c5.large"
  name        = "tf-q1-${count.index}"
  nics {
      network_id = data.vra_network.this.id
  }
  
  tags {
    key   = "OS"
    value = "Windows"
  }
  timeouts {
    create = "20m"
    delete = "20m"
    update = "20m"
  }

  disks {
    block_device_id = vra_block_device.vms.id
    name = "disk2"
  }

  boot_config {
      content = <<EOF
  runcmd:
    - New-Item -Path "C:\temp\" -Name "logfiles" -ItemType "directory"
    EOF
  }
  depends_on = [vra_block_device.vms]

}

**Comment by mdittbrenner215** [comment]
Second run to detach drive i ran it like:


provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure = "true"
}

data "vra_cloud_account_vsphere" "this" {
  name = var.cloud_account
}
data "vra_project" "this" {
  name = var.project
}

data "vra_network" "this" {
  name = "xxx.xxx.xxx.xxx"
  
}

 resource "vra_block_device" "vms" {
  capacity_in_gb =   500
 	name         =   "terraform_vra_block_device"
 	project_id    =   data.vra_project.this.id

}

resource "vra_machine" "vms" {
  count = "${var.instance_count}"
  description = "terrafrom test machine"
  project_id  = data.vra_project.this.id
  image       = "Cloudbase-init"
  flavor      = "c5.large"
  name        = "tf-q1-${count.index}"
  nics {
      network_id = data.vra_network.this.id
  }
  
  tags {
    key   = "OS"
    value = "Windows"
  }
  timeouts {
    create = "20m"
    delete = "20m"
    update = "20m"
  }

  /*disks {
    block_device_id = vra_block_device.vms.id
    name = "disk2"
  }*/

  boot_config {
      content = <<EOF
  runcmd:
    - New-Item -Path "C:\temp\" -Name "logfiles" -ItemType "directory"
    EOF
  }
  }

**Comment by mdittbrenner215** [comment]
the second command should detach the drive, but not delete it. 
When looking in vcenter i still see the drive attached.

**Comment by dmettem** [comment]
@mdittbrenner215  Thank you for the config file and more details. I'll try to reproduce and possibly work on a fix at the earliest.

**Comment by dmettem** [comment]
Fixed in #98.

**Comment by dmettem** [comment]
@mdittbrenner215 Fixed in [v0.1.3](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.3) release. Please confirm if it's working for you.

**Comment by mdittbrenner215** [comment]
This is working now.  Closing issue.
