### ISSUE TITLE
Add disk to existing VM does not attach disk

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#90]
When modifying to attach an existing disk to a VM it does not attach.

      + disks {
          + block_device_id = "7f925b8589d8167559634b05ce105"
          + name            = "disk2"
        }

        nics {
            addresses          = []
            custom_properties  = {}
            device_index       = 0
            network_id         = "7f925b8589d816755962818e4c3a9"
            security_group_ids = []
        }

        tags {
            key   = "OS"
            value = "Windows"
        }

        timeouts {
            create = "20m"
            delete = "20m"
            update = "20m"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vra_machine.vms[0]: Modifying... [id=9f28f11f75e2a2cf]
vra_machine.vms[0]: Modifications complete after 3s [id=9f28f11f75e2a2cf]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

**Comment by mdittbrenner215** [comment]
Going into vsphere the second disk is not attached.

**Comment by dmettem** [comment]
Fixed in #98.

**Comment by dmettem** [comment]
@mdittbrenner215 Fixed in [v0.1.3](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.3) release. Please confirm if it's working for you.

**Comment by mdittbrenner215** [comment]
This is working now.  TY!
