### ISSUE TITLE
Create vRA blueprint resource

### ISSUE THREAD

**Issue by chrisd27519** [vmware/terraform-provider-vra#99]
Is it possible to add the creation of a blueprint as a terraform vRA resource? I see the ability in the blueprint API section, but I don’t see a blueprint resource in the current terraform provider. This would allow a terraform user to generate the vRA specific yaml and execute it through a single terraform plan, instead of requiring separate actions within vRA itself.

**Comment by dmettem** [comment]
WIP for both resource and data source of vra_blueprint.

**Comment by AnjaliMangal** [comment]
This is enhancement in plugin , should be available by 11/30 .

**Comment by dark2phoenix** [comment]
Hello.  Did this make the 11/30 estimate?  I don't see a release that would cover that time frame.

**Comment by dmettem** [comment]
Unfortunately, I couldn't get this in last week. I'll try to get this out at the earliest and update here.

**Comment by dmettem** [comment]
Fixed in #129.

**Comment by dmettem** [comment]
Released in [0.1.6](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.6).
